@startmindmap
title Resources for project RDS Postgres
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchLogs
++++ LogGroup (1)
+++ EC2
++++ Vpc (1)
++++ InternetGateway (1)
++++ InternetGatewayAttachment (1)
++++ Subnet (2)
++++ RouteTable (1)
++++ RouteTableAssociation (2)
++++ Route (1)
++++ SecurityGroup (1)
++++ SecurityGroupRuleIngress (1)
+++ IAM
++++ Policy (1)
+++ RDS
++++ DBSubnetGroup (1)
++++ DBInstance (1)
@endmindmap