@startmindmap
title Resources for project subscription-filter
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchLogs
++++ LogGroup (1)
++++ SubscriptionFilter (1)
+++ IAM
++++ Role (1)
++++ Policy (1)
+++ Lambda
++++ Function (1)
++++ Permission (1)
@endmindmap