@startmindmap
title Resources for project launchTemplate
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ KeyPair (1)
++++ Vpc (1)
++++ SecurityGroup (1)
++++ SecurityGroupRuleIngress (1)
++++ LaunchTemplate (1)
+++ IAM
++++ Role (1)
++++ InstanceProfile (1)
@endmindmap