// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "EventBus",
    group: "CloudWatchEvents",
    properties: ({}) => ({
      Name: "EventbridgePipesSqsToEventbridgeStackeventbus5FFF751F",
    }),
  },
  {
    type: "Role",
    group: "IAM",
    properties: ({ config }) => ({
      RoleName:
        "EventbridgePipesSqsToEventbridgeStack-roleC7B7E775-149BW0CC9YR1V",
      AssumeRolePolicyDocument: {
        Version: "2012-10-17",
        Statement: [
          {
            Effect: "Allow",
            Principal: {
              Service: "pipes.amazonaws.com",
            },
            Action: "sts:AssumeRole",
          },
        ],
      },
      Policies: [
        {
          PolicyDocument: {
            Version: "2012-10-17",
            Statement: [
              {
                Action: [
                  "sqs:DeleteMessage",
                  "sqs:GetQueueAttributes",
                  "sqs:ReceiveMessage",
                ],
                Resource: `arn:aws:sqs:${
                  config.region
                }:${config.accountId()}:EventbridgePipesSqsToEventbridgeStack-sqsqueueE70CFDBB-JHT9xJPmXwFr`,
                Effect: "Allow",
              },
            ],
          },
          PolicyName: "sourcePolicy",
        },
        {
          PolicyDocument: {
            Version: "2012-10-17",
            Statement: [
              {
                Action: "events:PutEvents",
                Resource: `arn:aws:events:${
                  config.region
                }:${config.accountId()}:event-bus/EventbridgePipesSqsToEventbridgeStackeventbus5FFF751F`,
                Effect: "Allow",
              },
            ],
          },
          PolicyName: "targetPolicy",
        },
      ],
    }),
    dependencies: ({}) => ({
      queue:
        "EventbridgePipesSqsToEventbridgeStack-sqsqueueE70CFDBB-JHT9xJPmXwFr",
      eventBus: "EventbridgePipesSqsToEventbridgeStackeventbus5FFF751F",
    }),
  },
  {
    type: "Pipe",
    group: "Pipes",
    properties: ({}) => ({
      Name: "pipe-1oSrLv4grgjg",
      SourceParameters: {
        SqsQueueParameters: {
          BatchSize: 5,
          MaximumBatchingWindowInSeconds: 120,
        },
      },
      TargetParameters: {
        EventBridgeEventBusParameters: {
          DetailType: "OrderCreated",
          Source: "myapp.orders",
        },
        InputTemplate: `{
          "orderId": "<$.body.orderId>",
          "customerId": "<$.body.customerId>"
        }`,
      },
    }),
    dependencies: ({}) => ({
      iamRole:
        "EventbridgePipesSqsToEventbridgeStack-roleC7B7E775-149BW0CC9YR1V",
      sourceSQSQueue:
        "EventbridgePipesSqsToEventbridgeStack-sqsqueueE70CFDBB-JHT9xJPmXwFr",
      targetCloudWatchEventsEventBus:
        "EventbridgePipesSqsToEventbridgeStackeventbus5FFF751F",
    }),
  },
  {
    type: "Queue",
    group: "SQS",
    properties: ({}) => ({
      QueueName:
        "EventbridgePipesSqsToEventbridgeStack-sqsqueueE70CFDBB-JHT9xJPmXwFr",
    }),
  },
];
