@startmindmap
title Resources for project iam
skinparam monochrome true
+ Infra
++ aws
+++ ec2
++++ KeyPair (1)
+++++ kp
++++ Image (1)
+++++ Amazon Linux 2
++++ Instance (1)
+++++ web-iam
+++ iam
++++ Policy (4)
+++++ myPolicy-to-user
+++++ myPolicy-to-role
+++++ myPolicy-to-group
+++++ AmazonEKSWorkerNodePolicy
++++ Group (1)
+++++ Admin
++++ User (1)
+++++ Alice
++++ Role (1)
+++++ role-allow-assume-role
++++ InstanceProfile (1)
+++++ my-profile
@endmindmap