@startmindmap
title Resources for project load-balancer
skinparam monochrome true
+ Infra
++ azure
+++ Compute
++++ SshPublicKey (1)
++++ VirtualMachineScaleSet (1)
+++ Network
++++ LoadBalancer (1)
++++ LoadBalancerBackendAddressPool (1)
++++ NetworkSecurityGroup (1)
++++ PublicIPAddress (1)
++++ Subnet (1)
++++ VirtualNetwork (1)
+++ Resources
++++ ResourceGroup (1)
@endmindmap