// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

const createResources = ({ provider }) => {
  provider.S3.makeBucket({
    name: "grucloud-simple-bucket",
  });

  provider.S3.makeObject({
    name: "grucloud-simple-file-test",
    properties: ({}) => ({
      ContentType: "text/plain",
      ServerSideEncryption: "AES256",
      source: "s3/grucloud-simple-bucket/grucloud-simple-file-test.txt",
      Tags: [
        {
          Key: "Key1",
          Value: "Value1",
        },
        {
          Key: "Key2",
          Value: "Value2",
        },
      ],
    }),
    dependencies: () => ({
      bucket: "grucloud-simple-bucket",
    }),
  });
};

exports.createResources = createResources;
