@startmindmap
title Resources for project securityGroup
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ Vpc (1)
++++ SecurityGroup (2)
++++ SecurityGroupRuleIngress (2)
++++ SecurityGroupRuleEgress (1)
@endmindmap