// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Policy",
    group: "IAM",
    properties: ({}) => ({
      PolicyName: "lambda-policy",
      PolicyDocument: {
        Statement: [
          {
            Action: ["logs:*"],
            Effect: "Allow",
            Resource: "*",
          },
        ],
        Version: "2012-10-17",
      },
      Path: "/",
      Description: "Allow logs",
    }),
  },
  {
    type: "Role",
    group: "IAM",
    properties: ({}) => ({
      RoleName: "lambda-role",
      AssumeRolePolicyDocument: {
        Statement: [
          {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
              Service: "lambda.amazonaws.com",
            },
            Sid: "",
          },
        ],
        Version: "2012-10-17",
      },
    }),
    dependencies: ({}) => ({
      policies: ["lambda-policy"],
    }),
  },
  {
    type: "Function",
    group: "Lambda",
    properties: ({ getId }) => ({
      Configuration: {
        FunctionName: "lambda-hello-world",
        Handler: "helloworld.handler",
        Layers: [
          `${getId({
            type: "Layer",
            group: "Lambda",
            name: "lambda-layer",
            path: "live.LayerVersionArn",
          })}`,
        ],
        Runtime: "nodejs14.x",
      },
      Tags: {
        mykey: "value",
      },
    }),
    dependencies: ({}) => ({
      layers: ["lambda-layer"],
      role: "lambda-role",
    }),
  },
  {
    type: "Layer",
    group: "Lambda",
    properties: ({}) => ({
      LayerName: "lambda-layer",
      Description: "My Layer",
      CompatibleRuntimes: ["nodejs"],
    }),
  },
];
