@startmindmap
title Resources for project helloworld
skinparam monochrome true
+ Infra
++ aws
+++ iam
++++ Policy (1)
+++++ lambda-policy
++++ Role (1)
+++++ lambda-role
+++ lambda
++++ Function (1)
+++++ lambda-hello-world-1
@endmindmap