@startmindmap
title Resources for project dns-validation-record-txt
skinparam monochrome true
+ Infra
++ aws
+++ route53
++++ HostedZone (1)
+++++ grucloud.org.
++++ Record (1)
+++++ txt.grucloud.org.
@endmindmap