// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Ipam",
    group: "EC2",
    name: "ipam",
    properties: ({ config }) => ({
      IpamRegion: `${config.region}`,
      Description: "",
      OperatingRegions: [
        {
          RegionName: `${config.region}`,
        },
      ],
    }),
  },
  {
    type: "IpamPool",
    group: "EC2",
    name: "pool-regional",
    properties: ({ config }) => ({
      IpamScopeType: "private",
      IpamRegion: `${config.region}`,
      Locale: `${config.region}`,
      Description: "",
      AutoImport: false,
      AddressFamily: "ipv4",
      AllocationMinNetmaskLength: 0,
      AllocationMaxNetmaskLength: 32,
    }),
    dependencies: ({}) => ({
      ipamPoolSource: "pool-top-level",
      ipamScope: "my-ipam-scope",
    }),
  },
  {
    type: "IpamPool",
    group: "EC2",
    name: "pool-top-level",
    properties: ({ config }) => ({
      IpamScopeType: "private",
      IpamRegion: `${config.region}`,
      Description: "",
      AutoImport: false,
      AddressFamily: "ipv4",
      AllocationMinNetmaskLength: 0,
      AllocationMaxNetmaskLength: 32,
    }),
    dependencies: ({}) => ({
      ipamScope: "my-ipam-scope",
    }),
  },
  {
    type: "IpamPoolCidr",
    group: "EC2",
    properties: ({}) => ({
      Cidr: "10.0.0.0/16",
    }),
    dependencies: ({}) => ({
      ipamPool: "pool-top-level",
    }),
  },
  {
    type: "IpamPoolCidr",
    group: "EC2",
    properties: ({}) => ({
      Cidr: "10.0.0.0/24",
    }),
    dependencies: ({}) => ({
      ipamPool: "pool-regional",
    }),
  },
  {
    type: "IpamScope",
    group: "EC2",
    name: "my-ipam-scope",
    properties: ({ config }) => ({
      IpamRegion: `${config.region}`,
      IpamScopeType: "private",
      IsDefault: false,
      Description: "",
    }),
    dependencies: ({}) => ({
      ipam: "ipam",
    }),
  },
  {
    type: "Vpc",
    group: "EC2",
    name: "vpc-in-pool",
    properties: ({}) => ({
      Ipv4NetmaskLength: "26",
    }),
    dependencies: ({}) => ({
      ipamPoolIpv4: "pool-regional",
    }),
  },
];
