@startmindmap
title Resources for project eventbridge-cross-account
skinparam monochrome true
+ Infra
++ aws-primary
+++ CloudWatchEvents
++++ EventBus (1)
++++ Rule (1)
++++ Target (1)
+++ IAM
++++ Role (3)
+++ Lambda
++++ Function (1)
++++ Permission (1)
-- aws-secondary
--- ApiGatewayV2
---- Api (1)
---- Deployment (1)
---- Integration (1)
---- Route (1)
---- Stage (1)
--- CloudWatchEvents
---- EventBus (1)
---- Rule (1)
---- Target (1)
--- Lambda
---- Function (1)
---- Permission (1)
@endmindmap