// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Instance",
    group: "EC2",
    name: "web-server-ec2-example",
    properties: ({ config }) => ({
      DisableApiStop: true,
      InstanceType: "t3.micro",
      Placement: {
        AvailabilityZone: `${config.region}a`,
      },
      Image: {
        Description: "Amazon Linux 2 AMI 2.0.20211001.1 x86_64 HVM gp2",
      },
    }),
    dependencies: ({}) => ({
      subnets: ["vpc-default::subnet-default-a"],
      keyPair: "kp-ec2-example",
      securityGroups: ["sg::vpc-default::default"],
    }),
  },
];
