@startmindmap
title Resources for project azure-postgresql
skinparam monochrome true
+ Infra
++ azure
+++ DBforPostgreSQL
++++ FirewallRule (1)
++++ Server (1)
+++ Resources
++++ ResourceGroup (1)
@endmindmap