@startmindmap
title Resources for project vpc-endpoint
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ Vpc (1)
++++ Subnet (1)
++++ RouteTable (1)
++++ RouteTableAssociation (1)
++++ VpcEndpoint (1)
++++ Route (1)
@endmindmap