@startmindmap
title Resources for project vpc-endpoint
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchLogs
++++ LogGroup (1)
+++ EC2
++++ Vpc (1)
++++ InternetGateway (1)
++++ InternetGatewayAttachment (1)
++++ Subnet (2)
++++ RouteTable (2)
++++ RouteTableAssociation (2)
++++ Route (2)
++++ VpcEndpoint (1)
@endmindmap