@startmindmap
title Resources for project aws-cloudwan-workshop-code
skinparam monochrome true
+ Infra
++ aws-cloudwan
+++ NetworkManager
++++ CoreNetwork (1)
++++ GlobalNetwork (1)
++++ SiteToSiteVpnAttachment (1)
++++ VpcAttachment (1)
-- aws-primary
--- EC2
---- CustomerGateway (1)
---- ElasticIpAddress (2)
---- InternetGateway (2)
---- InternetGatewayAttachment (2)
---- NatGateway (2)
---- Route (5)
---- RouteTable (9)
---- RouteTableAssociation (9)
---- Subnet (9)
---- Vpc (4)
---- VpnConnection (1)
---- VpnGateway (1)
---- VpnGatewayAttachment (1)
---- VpnGatewayRoutePropagation (1)
++ aws-secondary
+++ EC2
++++ ElasticIpAddress (2)
++++ InternetGateway (1)
++++ InternetGatewayAttachment (1)
++++ NatGateway (2)
++++ Route (4)
++++ RouteTable (8)
++++ RouteTableAssociation (8)
++++ Subnet (8)
++++ Vpc (3)
@endmindmap