@startmindmap
title Resources for project resource-share
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ InternetGateway (1)
++++ InternetGatewayAttachment (1)
++++ Route (1)
++++ RouteTable (1)
++++ RouteTableAssociation (1)
++++ Subnet (1)
++++ Vpc (1)
+++ Organisations
++++ Organisation (1)
+++ RAM
++++ PrincipalAssociation (2)
++++ ResourceAssociation (1)
++++ ResourceShare (1)
@endmindmap