// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Group",
    group: "IAM",
    properties: ({}) => ({
      GroupName: "my-group",
      AttachedPolicies: [
        {
          PolicyName: "AmazonEC2ReadOnlyAccess",
          PolicyArn: "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess",
        },
      ],
    }),
  },
];
