@startmindmap
title Resources for project ec2-ssm
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ KeyPair (1)
++++ Vpc (2)
++++ InternetGateway (1)
++++ InternetGatewayAttachment (1)
++++ Subnet (1)
++++ RouteTable (1)
++++ RouteTableAssociation (1)
++++ Route (1)
++++ SecurityGroup (4)
++++ SecurityGroupRuleIngress (5)
++++ SecurityGroupRuleEgress (1)
++++ Instance (2)
+++ IAM
++++ Role (1)
++++ InstanceProfile (1)
@endmindmap