// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Vpc",
    group: "EC2",
    name: "project-test-vpc",
    properties: ({}) => ({
      CidrBlock: "10.0.0.0/16",
    }),
  },
  {
    type: "InternetGateway",
    group: "EC2",
    name: "project-test-igw",
    dependencies: () => ({
      vpc: "project-test-vpc",
    }),
  },
  {
    type: "Subnet",
    group: "EC2",
    name: "project-test-subnet-private1-us-east-1a",
    properties: ({ config }) => ({
      CidrBlock: "10.0.128.0/20",
      AvailabilityZone: `${config.region}a`,
    }),
    dependencies: () => ({
      vpc: "project-test-vpc",
    }),
  },
  {
    type: "Subnet",
    group: "EC2",
    name: "project-test-subnet-private2-us-east-1b",
    properties: ({ config }) => ({
      CidrBlock: "10.0.144.0/20",
      AvailabilityZone: `${config.region}b`,
    }),
    dependencies: () => ({
      vpc: "project-test-vpc",
    }),
  },
  {
    type: "Subnet",
    group: "EC2",
    name: "project-test-subnet-public1-us-east-1a",
    properties: ({ config }) => ({
      CidrBlock: "10.0.0.0/20",
      AvailabilityZone: `${config.region}a`,
    }),
    dependencies: () => ({
      vpc: "project-test-vpc",
    }),
  },
  {
    type: "Subnet",
    group: "EC2",
    name: "project-test-subnet-public2-us-east-1b",
    properties: ({ config }) => ({
      CidrBlock: "10.0.16.0/20",
      AvailabilityZone: `${config.region}b`,
    }),
    dependencies: () => ({
      vpc: "project-test-vpc",
    }),
  },
  {
    type: "RouteTable",
    group: "EC2",
    name: "project-test-rtb-private1-us-east-1a",
    dependencies: () => ({
      vpc: "project-test-vpc",
    }),
  },
  {
    type: "RouteTable",
    group: "EC2",
    name: "project-test-rtb-private2-us-east-1b",
    dependencies: () => ({
      vpc: "project-test-vpc",
    }),
  },
  {
    type: "RouteTable",
    group: "EC2",
    name: "project-test-rtb-public1-us-east-1a",
    dependencies: () => ({
      vpc: "project-test-vpc",
    }),
  },
  {
    type: "RouteTable",
    group: "EC2",
    name: "project-test-rtb-public2-us-east-1b",
    dependencies: () => ({
      vpc: "project-test-vpc",
    }),
  },
  {
    type: "RouteTableAssociation",
    group: "EC2",
    dependencies: () => ({
      routeTable: "project-test-rtb-private1-us-east-1a",
      subnet: "project-test-subnet-private1-us-east-1a",
    }),
  },
  {
    type: "RouteTableAssociation",
    group: "EC2",
    dependencies: () => ({
      routeTable: "project-test-rtb-private2-us-east-1b",
      subnet: "project-test-subnet-private2-us-east-1b",
    }),
  },
  {
    type: "RouteTableAssociation",
    group: "EC2",
    dependencies: () => ({
      routeTable: "project-test-rtb-public1-us-east-1a",
      subnet: "project-test-subnet-public1-us-east-1a",
    }),
  },
  {
    type: "RouteTableAssociation",
    group: "EC2",
    dependencies: () => ({
      routeTable: "project-test-rtb-public2-us-east-1b",
      subnet: "project-test-subnet-public2-us-east-1b",
    }),
  },
  {
    type: "Route",
    group: "EC2",
    dependencies: () => ({
      routeTable: "project-test-rtb-private1-us-east-1a",
    }),
  },
  {
    type: "Route",
    group: "EC2",
    dependencies: () => ({
      routeTable: "project-test-rtb-private2-us-east-1b",
    }),
  },
  {
    type: "Route",
    group: "EC2",
    properties: ({}) => ({
      DestinationCidrBlock: "0.0.0.0/0",
    }),
    dependencies: () => ({
      routeTable: "project-test-rtb-public1-us-east-1a",
      ig: "project-test-igw",
    }),
  },
  {
    type: "Route",
    group: "EC2",
    properties: ({}) => ({
      DestinationCidrBlock: "0.0.0.0/0",
    }),
    dependencies: () => ({
      routeTable: "project-test-rtb-public2-us-east-1b",
      ig: "project-test-igw",
    }),
  },
];
