// Generated by aws2gc
const { get } = require("rubico");
const { AwsProvider } = require("@grucloud/provider-aws");

const createResources = ({ provider }) => {
  provider.ec2.makeVpc({
    name: get("config.ec2.Vpc.vpcModuleLoadBalancer.name"),
    namespace: "VPC",
    properties: get("config.ec2.Vpc.vpcModuleLoadBalancer.properties"),
  });

  provider.ec2.makeSubnet({
    name: get("config.ec2.Subnet.subnetPublicA.name"),
    namespace: "VPC",
    properties: get("config.ec2.Subnet.subnetPublicA.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.ec2.Vpc.vpcModuleLoadBalancer,
    }),
  });

  provider.ec2.makeSubnet({
    name: get("config.ec2.Subnet.subnetPublicB.name"),
    namespace: "VPC",
    properties: get("config.ec2.Subnet.subnetPublicB.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.ec2.Vpc.vpcModuleLoadBalancer,
    }),
  });

  provider.ec2.makeInternetGateway({
    name: get("config.ec2.InternetGateway.internetGateway.name"),
    namespace: "VPC",
    dependencies: ({ resources }) => ({
      vpc: resources.ec2.Vpc.vpcModuleLoadBalancer,
    }),
  });

  provider.ec2.makeRouteTable({
    name: get("config.ec2.RouteTable.routeTablePublic.name"),
    namespace: "VPC",
    dependencies: ({ resources }) => ({
      vpc: resources.ec2.Vpc.vpcModuleLoadBalancer,
      subnets: [
        resources.ec2.Subnet.subnetPublicA,
        resources.ec2.Subnet.subnetPublicB,
      ],
    }),
  });

  provider.ec2.makeRoute({
    name: get("config.ec2.Route.routePublic.name"),
    namespace: "VPC",
    properties: get("config.ec2.Route.routePublic.properties"),
    dependencies: ({ resources }) => ({
      routeTable: resources.ec2.RouteTable.routeTablePublic,
      ig: resources.ec2.InternetGateway.internetGateway,
    }),
  });

  provider.ec2.makeSecurityGroup({
    name: get("config.ec2.SecurityGroup.securityGroupLoadBalancer.name"),
    namespace: "LoadBalancer",
    properties: get(
      "config.ec2.SecurityGroup.securityGroupLoadBalancer.properties"
    ),
    dependencies: ({ resources }) => ({
      vpc: resources.ec2.Vpc.vpcModuleLoadBalancer,
    }),
  });

  provider.ec2.makeSecurityGroupRuleIngress({
    name: get("config.ec2.SecurityGroupRuleIngress.sgRuleIngressLbHttp.name"),
    namespace: "LoadBalancer",
    properties: get(
      "config.ec2.SecurityGroupRuleIngress.sgRuleIngressLbHttp.properties"
    ),
    dependencies: ({ resources }) => ({
      securityGroup: resources.ec2.SecurityGroup.securityGroupLoadBalancer,
    }),
  });

  provider.ec2.makeSecurityGroupRuleIngress({
    name: get("config.ec2.SecurityGroupRuleIngress.sgRuleIngressLbHttps.name"),
    namespace: "LoadBalancer",
    properties: get(
      "config.ec2.SecurityGroupRuleIngress.sgRuleIngressLbHttps.properties"
    ),
    dependencies: ({ resources }) => ({
      securityGroup: resources.ec2.SecurityGroup.securityGroupLoadBalancer,
    }),
  });

  provider.acm.makeCertificate({
    name: get("config.acm.Certificate.modAwsLoadBalancerGrucloudOrg.name"),
    namespace: "Certificate",
    properties: get(
      "config.acm.Certificate.modAwsLoadBalancerGrucloudOrg.properties"
    ),
  });

  provider.elb.makeLoadBalancer({
    name: get("config.elb.LoadBalancer.loadBalancer.name"),
    namespace: "LoadBalancer",
    properties: get("config.elb.LoadBalancer.loadBalancer.properties"),
    dependencies: ({ resources }) => ({
      subnets: [
        resources.ec2.Subnet.subnetPublicA,
        resources.ec2.Subnet.subnetPublicB,
      ],
      securityGroups: [resources.ec2.SecurityGroup.securityGroupLoadBalancer],
    }),
  });

  provider.elb.makeTargetGroup({
    name: get("config.elb.TargetGroup.targetGroupRest.name"),
    namespace: "LoadBalancer",
    properties: get("config.elb.TargetGroup.targetGroupRest.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.ec2.Vpc.vpcModuleLoadBalancer,
    }),
  });

  provider.elb.makeTargetGroup({
    name: get("config.elb.TargetGroup.targetGroupWeb.name"),
    namespace: "LoadBalancer",
    properties: get("config.elb.TargetGroup.targetGroupWeb.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.ec2.Vpc.vpcModuleLoadBalancer,
    }),
  });

  provider.elb.makeListener({
    name: get("config.elb.Listener.listenerHttp.name"),
    namespace: "LoadBalancer",
    properties: get("config.elb.Listener.listenerHttp.properties"),
    dependencies: ({ resources }) => ({
      loadBalancer: resources.elb.LoadBalancer.loadBalancer,
      targetGroup: resources.elb.TargetGroup.targetGroupWeb,
    }),
  });

  provider.elb.makeListener({
    name: get("config.elb.Listener.listenerHttps.name"),
    namespace: "LoadBalancer",
    properties: get("config.elb.Listener.listenerHttps.properties"),
    dependencies: ({ resources }) => ({
      loadBalancer: resources.elb.LoadBalancer.loadBalancer,
      targetGroup: resources.elb.TargetGroup.targetGroupWeb,
      certificate: resources.acm.Certificate.modAwsLoadBalancerGrucloudOrg,
    }),
  });

  provider.elb.makeRule({
    name: get("config.elb.Rule.ruleHttpRedirectHttps.name"),
    namespace: "LoadBalancer",
    properties: () => config.elb.Rule.ruleHttpRedirectHttps.properties,
    dependencies: ({ resources }) => ({
      listener: resources.elb.Listener.listenerHttp,
    }),
  });

  provider.elb.makeRule({
    name: get("config.elb.Rule.ruleRestHttps.name"),
    namespace: "LoadBalancer",
    properties: () => config.elb.Rule.ruleRestHttps.properties,
    dependencies: ({ resources }) => ({
      listener: resources.elb.Listener.listenerHttps,
      targetGroup: resources.elb.TargetGroup.targetGroupRest,
    }),
  });

  provider.elb.makeRule({
    name: get("config.elb.Rule.ruleWebHttps.name"),
    namespace: "LoadBalancer",
    properties: () => config.elb.Rule.ruleWebHttps.properties,
    dependencies: ({ resources }) => ({
      listener: resources.elb.Listener.listenerHttps,
      targetGroup: resources.elb.TargetGroup.targetGroupWeb,
    }),
  });

  provider.route53Domain.useDomain({
    name: get("config.route53Domain.Domain.grucloudOrg.name"),
  });

  provider.route53.makeHostedZone({
    name: get("config.route53.HostedZone.modAwsLoadBalancerGrucloudOrg.name"),
    dependencies: ({ resources }) => ({
      domain: resources.route53Domain.Domain.grucloudOrg,
    }),
  });

  provider.route53.makeRecord({
    name: get(
      "config.route53.Record.certificateValidationModAwsLoadBalancerGrucloudOrg.name"
    ),
    namespace: "Certificate",
    dependencies: ({ resources }) => ({
      hostedZone: resources.route53.HostedZone.modAwsLoadBalancerGrucloudOrg,
      certificate: resources.acm.Certificate.modAwsLoadBalancerGrucloudOrg,
    }),
  });

  provider.route53.makeRecord({
    name: get(
      "config.route53.Record.loadBalancerDnsRecordAliasModAwsLoadBalancerGrucloudOrg.name"
    ),
    namespace: "LoadBalancer",
    dependencies: ({ resources }) => ({
      hostedZone: resources.route53.HostedZone.modAwsLoadBalancerGrucloudOrg,
      loadBalancer: resources.elb.LoadBalancer.loadBalancer,
    }),
  });
};

exports.createResources = createResources;

exports.createStack = async ({ createProvider }) => {
  const provider = createProvider(AwsProvider, { config: require("./config") });
  createResources({
    provider,
  });

  return {
    provider,
  };
};
