@startmindmap
title Resources for project lambda-secrets-manager-extension-python
skinparam monochrome true
+ Infra
++ aws
+++ IAM
++++ Role (1)
+++ Lambda
++++ Function (1)
+++ SecretsManager
++++ Secret (1)
@endmindmap