@startmindmap
title Resources for project placement-group-cluster
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ Vpc (1)
++++ Subnet (1)
++++ SecurityGroup (1)
++++ Instance (1)
++++ PlacementGroup (1)
@endmindmap