// Generated by aws2gc
const { AwsProvider } = require("@grucloud/provider-aws");

const createResources = ({ provider }) => {
  provider.ACM.makeCertificate({
    name: "example-module-aws-certificate.grucloud.org",
    properties: ({ config }) => ({
      DomainName: "example-module-aws-certificate.grucloud.org",
    }),
  });

  provider.Route53Domains.useDomain({
    name: "grucloud.org",
  });

  provider.Route53.makeHostedZone({
    name: "example-module-aws-certificate.grucloud.org.",
    dependencies: ({ resources }) => ({
      domain: resources.Route53Domains.Domain.grucloudOrg,
    }),
  });

  provider.Route53.makeRecord({
    name: "certificate-validation-example-module-aws-certificate.grucloud.org.",
    dependencies: ({ resources }) => ({
      hostedZone:
        resources.Route53.HostedZone.exampleModuleAwsCertificateGrucloudOrg,
      certificate:
        resources.ACM.Certificate.exampleModuleAwsCertificateGrucloudOrg,
    }),
  });
};

exports.createResources = createResources;

exports.createStack = async ({ createProvider }) => {
  const provider = createProvider(AwsProvider, { config: require("./config") });
  createResources({
    provider,
  });

  return {
    provider,
  };
};
