@startmindmap
title Resources for project Azure VM
skinparam monochrome true
+ Infra
++ azure
+++ Compute
++++ VirtualMachine (1)
+++ Network
++++ NetworkInterface (1)
++++ NetworkSecurityGroup (1)
++++ PublicIPAddress (1)
++++ Subnet (1)
++++ VirtualNetwork (1)
+++ Resources
++++ ResourceGroup (1)
@endmindmap