// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Repository",
    group: "ECR",
    properties: ({}) => ({
      repositoryName: "my-repo",
      imageTagMutability: "MUTABLE",
      imageScanningConfiguration: {
        scanOnPush: false,
      },
      encryptionConfiguration: {
        encryptionType: "AES256",
      },
    }),
  },
  {
    type: "InstanceProfile",
    group: "IAM",
    name: "EC2InstanceProfileForImageBuilder",
    dependencies: ({}) => ({
      roles: ["EC2InstanceProfileForImageBuilder"],
    }),
  },
  {
    type: "Role",
    group: "IAM",
    properties: ({}) => ({
      RoleName: "EC2InstanceProfileForImageBuilder",
      AssumeRolePolicyDocument: {
        Version: "2012-10-17",
        Statement: [
          {
            Effect: "Allow",
            Principal: {
              Service: "ec2.amazonaws.com",
            },
            Action: "sts:AssumeRole",
          },
        ],
      },
      AttachedPolicies: [
        {
          PolicyName: "AmazonSSMManagedInstanceCore",
          PolicyArn: "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
        },
        {
          PolicyName: "EC2InstanceProfileForImageBuilder",
          PolicyArn:
            "arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder",
        },
        {
          PolicyName: "EC2InstanceProfileForImageBuilderECRContainerBuilds",
          PolicyArn:
            "arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds",
        },
      ],
    }),
  },
  {
    type: "ContainerRecipe",
    group: "Imagebuilder",
    properties: ({}) => ({
      semanticVersion: "1.0.0",
      components: [
        {
          componentArn:
            "arn:aws:imagebuilder:us-east-1:aws:component/amazon-cloudwatch-agent-linux/x.x.x",
        },
      ],
      containerType: "DOCKER",
      dockerfileTemplateData: `FROM {{{ imagebuilder:parentImage }}}
{{{ imagebuilder:environments }}}
{{{ imagebuilder:components }}}`,
      encrypted: true,
      instanceConfiguration: {
        blockDeviceMappings: [],
        image: "ami-00eb0dc604a8124fd",
      },
      name: "my-repo",
      parentImage:
        "arn:aws:imagebuilder:us-east-1:aws:image/amazon-linux-x86-2/x.x.x",
      platform: "Linux",
      targetRepository: {
        repositoryName: "my-repo",
        service: "ECR",
      },
      workingDirectory: "/tmp",
    }),
  },
];
