@startmindmap
title Resources for project vpn-aws-azure
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ CustomerGateway (1)
++++ Vpc (1)
++++ Subnet (1)
++++ RouteTable (1)
++++ Route (1)
++++ SecurityGroup (1)
++++ SecurityGroupRuleIngress (3)
++++ Instance (1)
++++ VpcEndpoint (3)
++++ VpnGateway (1)
++++ VpnGatewayAttachment (1)
++++ VpnConnection (1)
++++ VpnConnectionRoute (1)
+++ IAM
++++ Role (1)
++++ InstanceProfile (1)
-- azure
--- Compute
---- SshPublicKey (1)
---- VirtualMachine (1)
---- VirtualMachineExtension (1)
--- Network
---- LocalNetworkGateway (2)
---- NetworkInterface (1)
---- NetworkSecurityGroup (1)
---- PublicIPAddress (1)
---- Route (1)
---- RouteTable (1)
---- Subnet (2)
---- VirtualNetwork (1)
---- VirtualNetworkGateway (1)
---- VirtualNetworkGatewayConnection (2)
---- VirtualNetworkGatewayConnectionSharedKey (2)
--- Resources
---- ResourceGroup (1)
@endmindmap