@startmindmap
title Resources for project vpn-aws-azure
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ CustomerGateway (1)
++++ Vpc (1)
++++ Subnet (1)
++++ RouteTable (1)
++++ Route (1)
++++ VpnGateway (1)
++++ VpnGatewayAttachment (1)
++++ VpnConnection (1)
-- azure
--- Network
---- LocalNetworkGateway (2)
---- PublicIPAddress (1)
---- Route (1)
---- RouteTable (1)
---- Subnet (2)
---- VirtualNetwork (1)
---- VirtualNetworkGateway (1)
---- VirtualNetworkGatewayConnection (2)
---- VirtualNetworkGatewayConnectionSharedKey (2)
--- Resources
---- ResourceGroup (1)
@endmindmap