@startmindmap
title Resources for project code-pipeline-simple
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchLogs
++++ LogGroup (1)
+++ CodeBuild
++++ Project (1)
+++ CodePipeline
++++ Pipeline (1)
+++ CodeStarConnections
++++ Connection (1)
+++ IAM
++++ Role (2)
++++ Policy (2)
+++ S3
++++ Bucket (1)
@endmindmap