@startmindmap
title Resources for project kinesis-stream
skinparam monochrome true
+ Infra
++ aws
+++ IAM
++++ Role (1)
++++ Policy (1)
+++ Kinesis
++++ Stream (1)
+++ Lambda
++++ EventSourceMapping (1)
++++ Function (1)
@endmindmap