@startmindmap
title Resources for project codegurureviewer-simple
skinparam monochrome true
+ Infra
++ aws
+++ CodeCommit
++++ Repository (1)
+++ CodeGuruReviewer
++++ RepositoryAssociation (1)
@endmindmap