@startmindmap
title Resources for project launchTemplate-simple
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ KeyPair (1)
++++ Vpc (1)
++++ Subnet (1)
++++ SecurityGroup (1)
++++ SecurityGroupRuleIngress (1)
++++ Instance (1)
++++ LaunchTemplate (1)
+++ IAM
++++ InstanceProfile (1)
++++ Role (1)
@endmindmap