@startmindmap
title Resources for project iam
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ Instance (1)
+++ IAM
++++ User (1)
++++ Group (1)
++++ Role (1)
++++ Policy (4)
++++ InstanceProfile (1)
@endmindmap