// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Address",
    group: "compute",
    properties: ({}) => ({
      name: "ip-vpn-1",
      description: "",
      networkTier: "PREMIUM",
      addressType: "EXTERNAL",
    }),
  },
  {
    type: "ForwardingRule",
    group: "compute",
    properties: ({}) => ({
      name: "vpn-1-rule-esp",
      description: "",
      IPProtocol: "ESP",
      loadBalancingScheme: "EXTERNAL",
      networkTier: "PREMIUM",
    }),
    dependencies: ({}) => ({
      address: "ip-vpn-1",
      targetVpnGateway: "vpn-1",
    }),
  },
  {
    type: "ForwardingRule",
    group: "compute",
    properties: ({}) => ({
      name: "vpn-1-rule-udp4500",
      description: "",
      IPProtocol: "UDP",
      portRange: "4500-4500",
      loadBalancingScheme: "EXTERNAL",
      networkTier: "PREMIUM",
    }),
    dependencies: ({}) => ({
      address: "ip-vpn-1",
      targetVpnGateway: "vpn-1",
    }),
  },
  {
    type: "ForwardingRule",
    group: "compute",
    properties: ({}) => ({
      name: "vpn-1-rule-udp500",
      description: "",
      IPProtocol: "UDP",
      portRange: "500-500",
      loadBalancingScheme: "EXTERNAL",
      networkTier: "PREMIUM",
    }),
    dependencies: ({}) => ({
      address: "ip-vpn-1",
      targetVpnGateway: "vpn-1",
    }),
  },
  {
    type: "Network",
    group: "compute",
    properties: ({}) => ({
      description: "Managed By GruCloud",
      autoCreateSubnetworks: false,
      name: "network",
      routingConfig: {
        routingMode: "REGIONAL",
      },
    }),
  },
  {
    type: "Route",
    group: "compute",
    properties: ({}) => ({
      name: "vpn-1-tunnel-1-route-1",
      description: "",
      destRange: "10.0.0.0/16",
      priority: 1000,
    }),
    dependencies: ({}) => ({
      network: "network",
      vpnTunnel: "vpn-1-tunnel-1",
    }),
  },
  {
    type: "Subnetwork",
    group: "compute",
    properties: ({}) => ({
      name: "subnet-1",
      ipCidrRange: "10.0.0.0/24",
    }),
    dependencies: ({}) => ({
      network: "network",
    }),
  },
  {
    type: "TargetVpnGateway",
    group: "compute",
    properties: ({}) => ({
      name: "vpn-1",
      description: "",
    }),
    dependencies: ({}) => ({
      network: "network",
    }),
  },
  {
    type: "VpnTunnel",
    group: "compute",
    properties: ({}) => ({
      name: "vpn-1-tunnel-1",
      description: "",
      peerIp: "50.1.2.3",
      sharedSecret: process.env.VPN_1_TUNNEL_1_SHAREDSECRET,
      ikeVersion: 2,
      localTrafficSelector: ["0.0.0.0/0"],
      remoteTrafficSelector: ["0.0.0.0/0"],
    }),
    dependencies: ({}) => ({
      targetVpnGateway: "vpn-1",
    }),
  },
];
