@startmindmap
title Resources for project lambda-rekognition
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchEvents
++++ Rule (1)
++++ Target (1)
+++ IAM
++++ Role (1)
+++ Lambda
++++ Function (1)
++++ Permission (1)
@endmindmap