@startmindmap
title Resources for project elasticache-redis
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ Vpc (1)
++++ Subnet (2)
++++ RouteTable (2)
++++ RouteTableAssociation (2)
+++ ElastiCache
++++ CacheCacheSubnetGroup (1)
++++ User (1)
++++ UserGroup (1)
@endmindmap