// Generated by aws2gc
const { get } = require("rubico");
const { AwsProvider } = require("@grucloud/provider-aws");

const createResources = ({ provider }) => {
  provider.EC2.makeVpc({
    name: get("config.EC2.Vpc.vpc.name"),
    namespace: "VPC",
    properties: get("config.EC2.Vpc.vpc.properties"),
  });

  provider.EC2.makeSubnet({
    name: get("config.EC2.Subnet.subnetPrivateA.name"),
    namespace: "VPC",
    properties: get("config.EC2.Subnet.subnetPrivateA.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
    }),
  });

  provider.EC2.makeSubnet({
    name: get("config.EC2.Subnet.subnetPrivateB.name"),
    namespace: "VPC",
    properties: get("config.EC2.Subnet.subnetPrivateB.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
    }),
  });

  provider.EC2.makeSubnet({
    name: get("config.EC2.Subnet.subnetPublicA.name"),
    namespace: "VPC",
    properties: get("config.EC2.Subnet.subnetPublicA.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
    }),
  });

  provider.EC2.makeSubnet({
    name: get("config.EC2.Subnet.subnetPublicB.name"),
    namespace: "VPC",
    properties: get("config.EC2.Subnet.subnetPublicB.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
    }),
  });

  provider.EC2.makeKeyPair({
    name: get("config.EC2.KeyPair.kpPostgresStateless.name"),
  });

  provider.EC2.makeElasticIpAddress({
    name: get("config.EC2.ElasticIpAddress.eipBastion.name"),
  });

  provider.EC2.makeElasticIpAddress({
    name: get("config.EC2.ElasticIpAddress.iep.name"),
    namespace: "VPC",
  });

  provider.EC2.makeInternetGateway({
    name: get("config.EC2.InternetGateway.internetGateway.name"),
    namespace: "VPC",
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
    }),
  });

  provider.EC2.makeNatGateway({
    name: get("config.EC2.NatGateway.natGateway.name"),
    namespace: "VPC",
    dependencies: ({ resources }) => ({
      subnet: resources.EC2.Subnet.subnetPublicA,
      eip: resources.EC2.ElasticIpAddress.iep,
    }),
  });

  provider.EC2.makeRouteTable({
    name: get("config.EC2.RouteTable.routeTablePrivateA.name"),
    namespace: "VPC",
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
      subnets: [resources.EC2.Subnet.subnetPrivateA],
    }),
  });

  provider.EC2.makeRouteTable({
    name: get("config.EC2.RouteTable.routeTablePrivateB.name"),
    namespace: "VPC",
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
      subnets: [resources.EC2.Subnet.subnetPrivateB],
    }),
  });

  provider.EC2.makeRouteTable({
    name: get("config.EC2.RouteTable.routeTablePublic.name"),
    namespace: "VPC",
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
      subnets: [
        resources.EC2.Subnet.subnetPublicA,
        resources.EC2.Subnet.subnetPublicB,
      ],
    }),
  });

  provider.EC2.makeRoute({
    name: get("config.EC2.Route.routePrivateA.name"),
    namespace: "VPC",
    properties: get("config.EC2.Route.routePrivateA.properties"),
    dependencies: ({ resources }) => ({
      routeTable: resources.EC2.RouteTable.routeTablePrivateA,
      natGateway: resources.EC2.NatGateway.natGateway,
    }),
  });

  provider.EC2.makeRoute({
    name: get("config.EC2.Route.routePrivateB.name"),
    namespace: "VPC",
    properties: get("config.EC2.Route.routePrivateB.properties"),
    dependencies: ({ resources }) => ({
      routeTable: resources.EC2.RouteTable.routeTablePrivateB,
      natGateway: resources.EC2.NatGateway.natGateway,
    }),
  });

  provider.EC2.makeRoute({
    name: get("config.EC2.Route.routePublic.name"),
    namespace: "VPC",
    properties: get("config.EC2.Route.routePublic.properties"),
    dependencies: ({ resources }) => ({
      routeTable: resources.EC2.RouteTable.routeTablePublic,
      ig: resources.EC2.InternetGateway.internetGateway,
    }),
  });

  provider.EC2.makeSecurityGroup({
    name: get("config.EC2.SecurityGroup.securityGroupPostgres.name"),
    properties: get(
      "config.EC2.SecurityGroup.securityGroupPostgres.properties"
    ),
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
    }),
  });

  provider.EC2.makeSecurityGroup({
    name: get("config.EC2.SecurityGroup.securityGroupPublic.name"),
    properties: get("config.EC2.SecurityGroup.securityGroupPublic.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
    }),
  });

  provider.EC2.makeSecurityGroupRuleIngress({
    name: get("config.EC2.SecurityGroupRuleIngress.sgRuleIngressPostgres.name"),
    properties: get(
      "config.EC2.SecurityGroupRuleIngress.sgRuleIngressPostgres.properties"
    ),
    dependencies: ({ resources }) => ({
      securityGroup: resources.EC2.SecurityGroup.securityGroupPostgres,
      securityGroupFrom: resources.EC2.SecurityGroup.securityGroupPublic,
    }),
  });

  provider.EC2.makeSecurityGroupRuleIngress({
    name: get(
      "config.EC2.SecurityGroupRuleIngress.sgRuleIngressSshBastion.name"
    ),
    properties: get(
      "config.EC2.SecurityGroupRuleIngress.sgRuleIngressSshBastion.properties"
    ),
    dependencies: ({ resources }) => ({
      securityGroup: resources.EC2.SecurityGroup.securityGroupPublic,
    }),
  });

  provider.EC2.makeInstance({
    name: get("config.EC2.Instance.bastion.name"),
    properties: get("config.EC2.Instance.bastion.properties"),
    dependencies: ({ resources }) => ({
      subnet: resources.EC2.Subnet.subnetPublicA,
      keyPair: resources.EC2.KeyPair.kpPostgresStateless,
      eip: resources.EC2.ElasticIpAddress.eipBastion,
      securityGroups: [resources.EC2.SecurityGroup.securityGroupPublic],
    }),
  });

  provider.RDS.makeDBCluster({
    name: get("config.RDS.DBCluster.clusterPostgresStateless.name"),
    properties: get("config.RDS.DBCluster.clusterPostgresStateless.properties"),
    dependencies: ({ resources }) => ({
      dbSubnetGroup: resources.RDS.DBSubnetGroup.subnetGroupPostgresStateless,
      securityGroups: [resources.EC2.SecurityGroup.securityGroupPostgres],
    }),
  });

  provider.RDS.makeDBSubnetGroup({
    name: get("config.RDS.DBSubnetGroup.subnetGroupPostgresStateless.name"),
    properties: get(
      "config.RDS.DBSubnetGroup.subnetGroupPostgresStateless.properties"
    ),
    dependencies: ({ resources }) => ({
      subnets: [
        resources.EC2.Subnet.subnetPrivateA,
        resources.EC2.Subnet.subnetPrivateB,
      ],
    }),
  });
};

exports.createResources = createResources;

exports.createStack = async ({ createProvider }) => {
  const provider = createProvider(AwsProvider, { config: require("./config") });
  createResources({
    provider,
  });

  return {
    provider,
  };
};
