@startmindmap
title Resources for project postgres-stateless
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchLogs
++++ LogGroup (1)
+++ EC2
++++ KeyPair (1)
++++ Vpc (1)
++++ InternetGateway (1)
++++ InternetGatewayAttachment (1)
++++ NatGateway (1)
++++ Subnet (4)
++++ RouteTable (3)
++++ RouteTableAssociation (4)
++++ Route (3)
++++ SecurityGroup (2)
++++ SecurityGroupRuleIngress (2)
++++ ElasticIpAddress (2)
++++ ElasticIpAddressAssociation (1)
++++ Instance (1)
+++ RDS
++++ DBSubnetGroup (1)
++++ DBCluster (1)
@endmindmap