@startmindmap
title Resources for project batch-eks
skinparam monochrome true
+ Infra
++ aws
+++ Batch
++++ ComputeEnvironment (1)
+++ EC2
++++ Vpc (1)
++++ Subnet (3)
++++ SecurityGroup (1)
+++ EKS
++++ Cluster (1)
+++ IAM
++++ Role (1)
@endmindmap