@startmindmap
title Resources for project RestApiGateway Lambda
skinparam monochrome true
+ Infra
++ aws
+++ APIGateway
++++ RestApi (1)
++++ Authorizer (1)
++++ Model (6)
++++ Resource (3)
++++ Method (4)
++++ Stage (1)
@endmindmap