// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "LogGroup",
    group: "CloudWatchLogs",
    properties: ({}) => ({
      logGroupName: "/aws/datasync",
    }),
  },
  {
    type: "LocationFsxOpenZfs",
    group: "DataSync",
    properties: ({}) => ({
      Protocol: {
        NFS: {
          MountOptions: {
            Version: "AUTOMATIC",
          },
        },
      },
    }),
    dependencies: ({}) => ({
      fsxFileSystem: "my-openzfs",
      securityGroups: ["sg::vpc-default::openzfs"],
    }),
  },
  {
    type: "LocationS3",
    group: "DataSync",
    properties: ({}) => ({
      S3StorageClass: "STANDARD",
    }),
    dependencies: ({}) => ({
      iamRole: "AWSDataSyncS3BucketAccess-gc-datasync-fsx-openzfs",
      s3Bucket: "gc-datasync-fsx-openzfs",
    }),
  },
  {
    type: "Task",
    group: "DataSync",
    properties: ({}) => ({
      Name: "my-task-openzfs",
      Options: {
        Gid: "INT_VALUE",
        LogLevel: "BASIC",
        PosixPermissions: "PRESERVE",
        Uid: "INT_VALUE",
      },
    }),
    dependencies: ({}) => ({
      logGroup: "/aws/datasync",
      destinationS3: "gc-datasync-fsx-openzfs",
      sourceFsxOpenZfs: "my-openzfs",
    }),
  },
  { type: "Vpc", group: "EC2", name: "vpc-default", isDefault: true },
  {
    type: "Subnet",
    group: "EC2",
    name: "subnet-default-f",
    isDefault: true,
    dependencies: ({}) => ({
      vpc: "vpc-default",
    }),
  },
  {
    type: "SecurityGroup",
    group: "EC2",
    name: "sg::vpc-default::default",
    isDefault: true,
    dependencies: ({}) => ({
      vpc: "vpc-default",
    }),
  },
  {
    type: "SecurityGroup",
    group: "EC2",
    properties: ({}) => ({
      GroupName: "openzfs",
      Description: "openzfs",
    }),
    dependencies: ({}) => ({
      vpc: "vpc-default",
    }),
  },
  {
    type: "SecurityGroupRuleIngress",
    group: "EC2",
    properties: ({}) => ({
      FromPort: 2049,
      IpProtocol: "tcp",
      IpRanges: [
        {
          CidrIp: "0.0.0.0/0",
        },
      ],
      ToPort: 2049,
    }),
    dependencies: ({}) => ({
      securityGroup: "sg::vpc-default::default",
    }),
  },
  {
    type: "SecurityGroupRuleIngress",
    group: "EC2",
    properties: ({}) => ({
      FromPort: 2049,
      IpProtocol: "tcp",
      IpRanges: [
        {
          CidrIp: "0.0.0.0/0",
        },
      ],
      ToPort: 2049,
    }),
    dependencies: ({}) => ({
      securityGroup: "sg::vpc-default::openzfs",
    }),
  },
  {
    type: "FileSystem",
    group: "FSx",
    name: "my-openzfs",
    properties: ({}) => ({
      FileSystemType: "OPENZFS",
      OpenZFSConfiguration: {
        AutomaticBackupRetentionDays: 7,
        CopyTagsToBackups: false,
        CopyTagsToVolumes: false,
        DailyAutomaticBackupStartTime: "08:30",
        DeploymentType: "SINGLE_AZ_2",
        DiskIopsConfiguration: {
          Mode: "AUTOMATIC",
        },
        ThroughputCapacity: 160,
        WeeklyMaintenanceStartTime: "6:04:00",
      },
      StorageCapacity: 64,
      StorageType: "SSD",
    }),
    dependencies: ({}) => ({
      subnets: ["vpc-default::subnet-default-f"],
    }),
  },
  {
    type: "Role",
    group: "IAM",
    properties: ({ config }) => ({
      RoleName: "AWSDataSyncS3BucketAccess-gc-datasync-fsx-openzfs",
      Path: "/service-role/",
      AssumeRolePolicyDocument: {
        Version: "2012-10-17",
        Statement: [
          {
            Effect: "Allow",
            Principal: {
              Service: "datasync.amazonaws.com",
            },
            Action: "sts:AssumeRole",
            Condition: {
              StringEquals: {
                "aws:SourceAccount": `${config.accountId()}`,
              },
              ArnLike: {
                "aws:SourceArn": `arn:aws:datasync:${
                  config.region
                }:${config.accountId()}:*`,
              },
            },
          },
        ],
      },
    }),
    dependencies: ({}) => ({
      policies: ["AWSDataSyncS3BucketAccess-gc-datasync-fsx-openzfs"],
    }),
  },
  {
    type: "Policy",
    group: "IAM",
    properties: ({}) => ({
      PolicyName: "AWSDataSyncS3BucketAccess-gc-datasync-fsx-openzfs",
      PolicyDocument: {
        Version: "2012-10-17",
        Statement: [
          {
            Action: [
              "s3:GetBucketLocation",
              "s3:ListBucket",
              "s3:ListBucketMultipartUploads",
            ],
            Effect: "Allow",
            Resource: "arn:aws:s3:::gc-datasync-fsx-openzfs",
          },
          {
            Action: [
              "s3:AbortMultipartUpload",
              "s3:DeleteObject",
              "s3:GetObject",
              "s3:ListMultipartUploadParts",
              "s3:PutObjectTagging",
              "s3:GetObjectTagging",
              "s3:PutObject",
            ],
            Effect: "Allow",
            Resource: "arn:aws:s3:::gc-datasync-fsx-openzfs/*",
          },
        ],
      },
      Path: "/service-role/",
    }),
  },
  {
    type: "Bucket",
    group: "S3",
    properties: ({}) => ({
      Name: "gc-datasync-fsx-openzfs",
      ServerSideEncryptionConfiguration: {
        Rules: [
          {
            ApplyServerSideEncryptionByDefault: {
              SSEAlgorithm: "AES256",
            },
            BucketKeyEnabled: true,
          },
        ],
      },
    }),
  },
];
