@startmindmap
title Resources for project secrets-rotation
skinparam monochrome true
+ Infra
++ aws
+++ IAM
++++ Policy (1)
++++ Role (1)
+++ Lambda
++++ Function (1)
++++ Permission (1)
+++ SecretsManager
++++ Secret (1)
++++ SecretRotation (1)
++++ ResourcePolicy (1)
@endmindmap