@startmindmap
title Resources for project dynamodb-lambda
skinparam monochrome true
+ Infra
++ aws
+++ DynamoDB
++++ Table (1)
+++ IAM
++++ Role (1)
+++ Lambda
++++ EventSourceMapping (1)
++++ Function (1)
@endmindmap