@startmindmap
title Resources for project directory-service-microsoft-ad
skinparam monochrome true
+ Infra
++ aws
+++ DirectoryService
++++ Directory (1)
++++ SharedDirectory (1)
+++ EC2
++++ Vpc (1)
++++ Subnet (2)
+++ Organisations
++++ Account (1)
@endmindmap