@startmindmap
title Resources for project ec2
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ KeyPair (1)
++++ Vpc (1)
++++ Subnet (1)
++++ SecurityGroup (1)
++++ ElasticIpAddress (1)
++++ ElasticIpAddressAssociation (1)
++++ Instance (1)
@endmindmap