@startmindmap
title Resources for project SecurityGroup source from itself
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ Vpc (1)
++++ SecurityGroup (2)
++++ SecurityGroupRuleIngress (2)
@endmindmap