@startmindmap
title Resources for project vm
skinparam monochrome true
+ Infra
++ google
+++ compute
++++ Address (1)
++++ Disk (1)
++++ Firewall (2)
++++ Instance (1)
+++ iam
++++ ServiceAccount (1)
@endmindmap