// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

const createResources = ({ provider }) => {
  provider.Network.makeNatGateway({
    properties: ({}) => ({
      name: "nat-gw",
      sku: {
        name: "Standard",
      },
      properties: {
        idleTimeoutInMinutes: 4,
      },
    }),
    dependencies: () => ({
      resourceGroup: "rg-natgateway",
      publicIpAddresses: ["rg-natgateway::ip-address"],
    }),
  });

  provider.Network.makePublicIPAddress({
    properties: ({}) => ({
      name: "ip-address",
      sku: {
        name: "Standard",
      },
      properties: {
        publicIPAllocationMethod: "Static",
      },
    }),
    dependencies: () => ({
      resourceGroup: "rg-natgateway",
    }),
  });

  provider.Network.makeSubnet({
    properties: ({}) => ({
      name: "default",
      properties: {
        addressPrefix: "10.0.0.0/24",
      },
    }),
    dependencies: () => ({
      resourceGroup: "rg-natgateway",
      virtualNetwork: "rg-natgateway::virtual-network",
    }),
  });

  provider.Network.makeVirtualNetwork({
    properties: ({}) => ({
      name: "virtual-network",
      properties: {
        addressSpace: {
          addressPrefixes: ["10.0.0.0/16"],
        },
      },
    }),
    dependencies: () => ({
      resourceGroup: "rg-natgateway",
    }),
  });

  provider.Resources.makeResourceGroup({
    properties: ({}) => ({
      name: "rg-natgateway",
    }),
  });
};

exports.createResources = createResources;
