@startmindmap
title Resources for project sfn-glue-terraform
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchEvents
++++ Rule (1)
++++ Target (1)
+++ Glue
++++ Job (1)
+++ IAM
++++ Role (3)
++++ Policy (1)
+++ S3
++++ Bucket (1)
+++ StepFunctions
++++ StateMachine (1)
@endmindmap