// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "InternetGateway",
    group: "EC2",
    name: "ig-default",
    isDefault: true,
  },
  {
    type: "ManagedPrefixList",
    group: "EC2",
    properties: ({}) => ({
      PrefixListName: "my-prefix",
      AddressFamily: "IPv4",
      MaxEntries: 6,
      Entries: [
        {
          Cidr: "10.0.0.0/24",
        },
        {
          Cidr: "10.0.1.0/24",
        },
      ],
    }),
  },
  {
    type: "Route",
    group: "EC2",
    dependencies: ({}) => ({
      ig: "ig-default",
      prefixList: "my-prefix",
      routeTable: "vpc-default::rt-default",
    }),
  },
  {
    type: "RouteTable",
    group: "EC2",
    name: "rt-default",
    isDefault: true,
    dependencies: ({}) => ({
      vpc: "vpc-default",
    }),
  },
  { type: "Vpc", group: "EC2", name: "vpc-default", isDefault: true },
];
