@startmindmap
title Resources for project apprunner-leaderboard
skinparam monochrome true
+ Infra
++ aws
+++ AppRunner
++++ Connection (1)
++++ Service (2)
++++ VpcConnector (1)
++++ VpcIngressConnection (1)
+++ EC2
++++ Vpc (1)
++++ Subnet (2)
++++ SecurityGroup (1)
++++ VpcEndpoint (1)
@endmindmap