@startmindmap
title Resources for project wafv2-apigateway-rest
skinparam monochrome true
+ Infra
++ aws
+++ APIGateway
++++ Account (1)
++++ ApiKey (1)
++++ RestApi (1)
++++ Stage (1)
+++ CloudWatchLogs
++++ LogGroup (1)
+++ IAM
++++ Role (1)
+++ WAFv2
++++ WebACL (1)
++++ WebACLAssociation (1)
@endmindmap