// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "AlternateAccount",
    group: "Account",
    properties: ({}) => ({
      AlternateContactType: "BILLING",
      EmailAddress: "frederic@mail.com",
      Name: "Frederic",
      PhoneNumber: "+336789123456",
      Title: "Mr",
    }),
  },
  {
    type: "AlternateAccount",
    group: "Account",
    properties: ({}) => ({
      AlternateContactType: "OPERATIONS",
      EmailAddress: "frederic@mail.com",
      Name: "Frederic",
      PhoneNumber: "+33678912345",
      Title: "Mr",
    }),
  },
  {
    type: "AlternateAccount",
    group: "Account",
    properties: ({}) => ({
      AlternateContactType: "SECURITY",
      EmailAddress: "frederic@mail.com",
      Name: "Frederic",
      PhoneNumber: "+33678912345",
      Title: "Ms",
    }),
  },
];
