@startmindmap
title Resources for project synthetics-simple
skinparam monochrome true
+ Infra
++ aws
+++ IAM
++++ Policy (1)
++++ Role (1)
+++ S3
++++ Bucket (1)
+++ Synthetics
++++ Canary (1)
@endmindmap