@startmindmap
title Resources for project eventbridge-pipes-sqs-to-lambda-with-stepfunction-enrichment
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchLogs
++++ LogGroup (1)
+++ DynamoDB
++++ Table (1)
+++ IAM
++++ Role (3)
+++ Lambda
++++ Function (1)
+++ Pipes
++++ Pipe (1)
+++ SQS
++++ Queue (2)
++++ QueueRedrivePolicy (1)
+++ StepFunctions
++++ StateMachine (1)
@endmindmap