@startmindmap
title Resources for project transit-gateway-peering
skinparam monochrome true
+ Infra
++ aws-primary
+++ EC2
++++ TransitGateway (1)
++++ TransitGatewayPeeringAttachment (1)
-- aws-secondary
--- EC2
---- TransitGateway (1)
@endmindmap