@startmindmap
title Resources for project transit-gateway
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ Vpc (1)
++++ Subnet (2)
++++ RouteTable (1)
++++ Route (1)
++++ TransitGateway (1)
++++ TransitGatewayRoute (1)
++++ TransitGatewayRouteTable (1)
++++ TransitGatewayVpcAttachment (1)
++++ TransitGatewayRouteTableAssociation (1)
++++ TransitGatewayRouteTablePropagation (1)
@endmindmap