@startmindmap
title Resources for project transit-gateway
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ Vpc (2)
++++ Subnet (4)
++++ RouteTable (3)
++++ RouteTableAssociation (2)
++++ Route (1)
++++ TransitGateway (1)
++++ TransitGatewayRoute (1)
++++ TransitGatewayRouteTable (1)
++++ TransitGatewayVpcAttachment (2)
++++ TransitGatewayRouteTableAssociation (2)
++++ TransitGatewayRouteTablePropagation (2)
@endmindmap