@startmindmap
title Resources for project batch-simple
skinparam monochrome true
+ Infra
++ aws
+++ Batch
++++ ComputeEnvironment (1)
++++ JobDefinition (1)
++++ JobQueue (1)
++++ SchedulingPolicy (1)
+++ EC2
++++ SecurityGroup (1)
++++ Subnet (2)
++++ Vpc (1)
+++ IAM
++++ InstanceProfile (1)
++++ Role (1)
@endmindmap