// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "LogGroup",
    group: "CloudWatchLogs",
    name: "my-loggroup",
    properties: ({}) => ({
      tags: {
        mytag: "myvalue",
      },
    }),
  },
];
