// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "MetricAlarm",
    group: "CloudWatch",
    properties: ({ config, getId }) => ({
      AlarmName:
        "healthcheck-grucloud-awsroute53-5dcc5fa2-2b2f-4735-9a2f-109415b1e977-Low-HealthCheckStatus",
      AlarmActions: [
        `arn:aws:sns:${config.region}:${config.accountId()}:healthcheck`,
      ],
      MetricName: "HealthCheckStatus",
      Namespace: "AWS/Route53",
      Statistic: "Minimum",
      Dimensions: [
        {
          Value: `${getId({
            type: "HealthCheck",
            group: "Route53",
            name: "heathcheck::HTTP::healthcheck.grucloud.org",
          })}`,
          Name: "HealthCheckId",
        },
      ],
      Period: 60,
      EvaluationPeriods: 1,
      DatapointsToAlarm: 1,
      Threshold: 1,
      ComparisonOperator: "LessThanThreshold",
    }),
    dependencies: ({}) => ({
      snsTopic: "healthcheck",
      route53HealhCheck: "heathcheck::HTTP::healthcheck.grucloud.org",
    }),
  },
  {
    type: "HealthCheck",
    group: "Route53",
    properties: ({}) => ({
      HealthCheckConfig: {
        EnableSNI: false,
        FailureThreshold: 3,
        FullyQualifiedDomainName: "healthcheck.grucloud.org",
        MeasureLatency: false,
        Port: 80,
        RequestInterval: 30,
        Type: "HTTP",
      },
    }),
  },
  { type: "Topic", group: "SNS", name: "healthcheck" },
];
