@startmindmap
title Resources for project appsync-cognito-lambda-cdk
skinparam monochrome true
+ Infra
++ aws
+++ AppSync
++++ DataSource (1)
++++ GraphqlApi (1)
++++ Resolver (1)
+++ CognitoIdentityServiceProvider
++++ UserPool (1)
++++ UserPoolClient (1)
+++ IAM
++++ Role (3)
+++ Lambda
++++ Function (1)
@endmindmap