@startmindmap
title Resources for project eks-lean
skinparam monochrome true
+ Infra
++ aws
+++ Route53Domains
++++ Domain (1)
+++ Route53
++++ HostedZone (1)
++++ Record (2)
+++ ACM
++++ Certificate (1)
+++ EC2
++++ Vpc (1)
++++ InternetGateway (1)
++++ Subnet (4)
++++ RouteTable (3)
++++ Route (3)
++++ ElasticIpAddress (1)
++++ NatGateway (1)
++++ SecurityGroup (4)
++++ SecurityGroupRuleIngress (5)
++++ SecurityGroupRuleEgress (1)
+++ IAM
++++ Policy (5)
++++ Role (2)
+++ KMS
++++ Key (1)
+++ EKS
++++ Cluster (1)
++++ NodeGroup (1)
+++ ELBv2
++++ LoadBalancer (1)
++++ TargetGroup (2)
++++ Listener (2)
++++ Rule (3)
-- k8s
--- Namespace (1)
--- ConfigMap (2)
--- StatefulSet (2)
--- Service (4)
--- Deployment (2)
@endmindmap