@startmindmap
title Resources for project comprehend-simple
skinparam monochrome true
+ Infra
++ aws
+++ Comprehend
++++ DocumentClassifier (1)
++++ EntityRecognizer (1)
+++ IAM
++++ Role (2)
++++ Policy (2)
+++ S3
++++ Bucket (1)
@endmindmap