@startmindmap
title Resources for project multiple
skinparam monochrome true
+ Infra
++ azure
+++ ContainerService
++++ ManagedCluster (1)
+++ Resources
++++ ResourceGroup (7)
+++ Authorization
++++ RoleAssignment (1)
+++ Compute
++++ SshPublicKey (3)
++++ VirtualMachine (2)
++++ VirtualMachineExtension (1)
++++ Disk (1)
++++ VirtualMachineScaleSet (1)
+++ Network
++++ NetworkInterface (2)
++++ NetworkSecurityGroup (3)
++++ PublicIPAddress (4)
++++ Subnet (4)
++++ VirtualNetwork (4)
++++ LoadBalancer (1)
++++ LoadBalancerBackendAddressPool (1)
++++ NatGateway (1)
+++ DBforPostgreSQL
++++ Configuration (1)
++++ FirewallRule (1)
++++ FlexibleServer (1)
+++ OperationalInsights
++++ Workspace (1)
+++ Web
++++ ContainerApp (1)
++++ KubeEnvironment (1)
@endmindmap