// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Instance",
    group: "EC2",
    name: "web-server-ec2-simple",
    properties: ({ config }) => ({
      InstanceType: "t2.micro",
      Image: {
        Description: "Amazon Linux 2 AMI 2.0.20211001.1 x86_64 HVM gp2",
      },
      Tags: [
        {
          Key: "mykey",
          Value: "myvalue",
        },
      ],
      Placement: {
        AvailabilityZone: `${config.region}d`,
      },
    }),
  },
];
