@startmindmap
title Resources for project ecs-simple
skinparam monochrome true
+ Infra
++ aws
+++ iam
++++ Policy (1)
++++ Role (1)
++++ InstanceProfile (1)
+++ ec2
++++ Vpc (1)
++++ Subnet (2)
++++ InternetGateway (1)
++++ RouteTable (1)
++++ Route (1)
++++ SecurityGroup (1)
++++ SecurityGroupRuleIngress (1)
+++ autoscaling
++++ AutoScalingGroup (1)
++++ LaunchConfiguration (1)
+++ ecs
++++ Cluster (1)
++++ CapacityProvider (1)
++++ TaskDefinition (1)
++++ Service (1)
@endmindmap