@startmindmap
title Resources for project ecs-simple
skinparam monochrome true
+ Infra
++ aws
+++ AutoScaling
++++ AutoScalingGroup (1)
++++ LaunchConfiguration (1)
+++ CloudWatch
++++ MetricAlarm (1)
+++ EC2
++++ Vpc (1)
++++ InternetGateway (1)
++++ InternetGatewayAttachment (1)
++++ Subnet (2)
++++ RouteTable (1)
++++ RouteTableAssociation (2)
++++ Route (1)
++++ SecurityGroup (1)
++++ SecurityGroupRuleIngress (1)
+++ ECS
++++ CapacityProvider (1)
++++ Cluster (1)
++++ Service (1)
++++ TaskDefinition (1)
+++ IAM
++++ InstanceProfile (1)
++++ Role (1)
@endmindmap