@startmindmap
title Resources for project eventbridge-pipes-sqs-to-eventbridge-cdk
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchEvents
++++ EventBus (1)
+++ IAM
++++ Role (1)
+++ Pipes
++++ Pipe (1)
+++ SQS
++++ Queue (1)
@endmindmap