@startmindmap
title Resources for project elasticache-memcached
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ Vpc (1)
++++ Subnet (2)
++++ RouteTable (2)
++++ RouteTableAssociation (2)
++++ SecurityGroup (1)
+++ ElastiCache
++++ CacheCluster (1)
++++ CacheParameterGroup (1)
++++ CacheSubnetGroup (1)
@endmindmap