@startmindmap
title Resources for project lambda-sns-filters-lambda
skinparam monochrome true
+ Infra
++ aws
+++ IAM
++++ Role (3)
+++ Lambda
++++ Function (3)
++++ Permission (2)
+++ SNS
++++ Topic (1)
++++ Subscription (2)
@endmindmap