@startmindmap
title Resources for project route-table-association
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ Vpc (1)
++++ InternetGateway (1)
++++ InternetGatewayAttachment (1)
++++ Subnet (2)
++++ RouteTable (1)
++++ RouteTableAssociation (2)
++++ Route (1)
@endmindmap