// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "ParameterGroup",
    group: "DAX",
    properties: ({}) => ({
      Description: " ",
      ParameterGroupName: "my-parameter-group",
      ParameterNameValues: [
        {
          ParameterName: "query-ttl-millis",
          ParameterValue: "18000002",
        },
        {
          ParameterName: "record-ttl-millis",
          ParameterValue: "18000002",
        },
      ],
    }),
  },
];
