@startmindmap
title Resources for project apigw-websocket-api-sfn-async
skinparam monochrome true
+ Infra
++ aws
+++ ApiGatewayV2
++++ Api (1)
++++ Deployment (1)
++++ Integration (1)
++++ IntegrationResponse (1)
++++ Route (1)
++++ RouteResponse (1)
++++ Stage (1)
+++ IAM
++++ Role (2)
+++ StepFunctions
++++ StateMachine (1)
@endmindmap