(cd aws/eks && npm run link)
(cd aws/ec2 && npm run link)
(cd aws/ec2-vpc && npm run link)
(cd aws/volume && npm run link)
(cd aws/s3 && npm run link)
(cd aws/s3-multiple && npm run link)
(cd aws/s3-simple && npm run link)
(cd aws/iam && npm run link)
(cd aws/certificate && npm run link)
(cd aws/website-https && npm run link)
(cd azure/ && npm run link)
(cd google/dns/github-page && npm run link)
(cd google/vm && npm run link)
(cd google/vm-simple && npm run link)
(cd google/vm-ssh-keys && npm run link)
(cd google/vm-network && npm run link)
(cd google/iam/iam-policy && npm run link)
(cd google/iam/iam-binding && npm run link)
(cd google/storage/simple && npm run link)
(cd google/storage/website-https && npm run link)
(cd mock/mock && npm run link)
(cd mock/mock-multi && npm run link)
(cd mock/mock-simple && npm run link)
(cd multi/ && npm run link)
(cd k8s/cert-manager && npm run link)
(cd k8s/aws-load-balancer && npm run link)
(cd k8s/starhackit/aws && npm run link)
(cd k8s/starhackit/minikube && npm run link)
(cd k8s/starhackit/base && npm run link)
(cd scaleway/ && npm run link)



