@startmindmap
title Resources for project dms-postgres-secret-manager
skinparam monochrome true
+ Infra
++ aws
+++ DMS
++++ Endpoint (1)
+++ IAM
++++ Role (1)
+++ SecretsManager
++++ Secret (1)
@endmindmap