@startmindmap
title Resources for project application-load-balancer-fargate-service
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchLogs
++++ LogGroup (1)
+++ EC2
++++ Vpc (1)
++++ InternetGateway (1)
++++ InternetGatewayAttachment (1)
++++ NatGateway (1)
++++ Subnet (6)
++++ RouteTable (6)
++++ RouteTableAssociation (6)
++++ Route (4)
++++ SecurityGroup (2)
++++ SecurityGroupRuleIngress (2)
++++ SecurityGroupRuleEgress (1)
++++ ElasticIpAddress (1)
+++ ECS
++++ Cluster (1)
++++ Service (1)
++++ TaskDefinition (1)
+++ ElasticLoadBalancingV2
++++ LoadBalancer (1)
++++ TargetGroup (1)
++++ Listener (1)
+++ IAM
++++ Role (2)
@endmindmap