@startmindmap
title Resources for project ApiGateway Auth0 Autorizer
skinparam monochrome true
+ Infra
++ aws
+++ ACM
++++ Certificate (1)
+++ ApiGatewayV2
++++ Api (1)
++++ ApiMapping (1)
++++ Authorizer (1)
++++ Deployment (1)
++++ DomainName (1)
++++ Integration (1)
++++ Route (1)
++++ Stage (1)
+++ CloudWatchLogs
++++ LogGroup (1)
+++ IAM
++++ Role (1)
++++ Policy (1)
+++ Lambda
++++ Function (1)
++++ Permission (1)
+++ Route53
++++ HostedZone (1)
++++ Record (2)
+++ Route53Domains
++++ Domain (1)
@endmindmap