const assert = require("assert");
const { pipe, tap } = require("rubico");

const { createAwsResource } = require("./AwsClient");

exports.createAwsService = ({
  package,
  client,
  type,
  region,
  propertiesDefault,
  omitProperties,
  inferName,
  dependencies,
  isDefault,
  findDefault,
  cannotBeDeleted,
  managedByOther,
  filterLive,
  findName,
  findId,
  ignoreErrorCodes,
  ignoreErrorMessages,
  getById,
  getList,
  create,
  update,
  destroy,
  getByName,
  configDefault,
  compare,
  environmentVariables,
  ignoreResource,
  tagger = () => ({}),
  getEndpointConfig,
  onDeployed,
  findDependencies,
  ...other
}) =>
  pipe([
    tap((params) => {
      assert(other);
    }),
    () => ({
      type,
      propertiesDefault,
      omitProperties,
      inferName,
      dependencies,
      filterLive,
      compare,
      environmentVariables,
      ignoreResource,
      onDeployed,
      Client: ({ spec, config, getContext }) =>
        createAwsResource({
          getContext,
          getEndpointConfig,
          model: {
            package,
            client,
            region,
            getById,
            getList,
            create,
            update,
            destroy,
            ignoreErrorCodes,
            ignoreErrorMessages,
          },
          getById,
          spec,
          config,
          isDefault,
          cannotBeDeleted,
          managedByOther,
          findName,
          findId,
          getList,
          create,
          update,
          destroy,
          getByName,
          configDefault,
          findDependencies,
          ...tagger({ config }),
        }),
      findDefault,
      ...other,
    }),
  ])();
