@startmindmap
title Resources for project appconfig-feature-flag-sam
skinparam monochrome true
+ Infra
++ aws
+++ ApiGatewayV2
++++ Api (1)
++++ Deployment (1)
++++ Integration (1)
++++ Route (1)
++++ Stage (1)
+++ AppConfig
++++ Application (1)
++++ ConfigurationProfile (1)
++++ Deployment (1)
++++ DeploymentStrategy (1)
++++ Environment (1)
++++ HostedConfigurationVersion (1)
+++ IAM
++++ Role (1)
+++ Lambda
++++ Function (1)
@endmindmap