@startmindmap
title Resources for project lambda-layer-ssm-parameters
skinparam monochrome true
+ Infra
++ aws
+++ IAM
++++ Role (1)
+++ Lambda
++++ Layer (1)
++++ Function (1)
++++ Permission (1)
+++ SSM
++++ Parameter (2)
@endmindmap