@startmindmap
title Resources for project graphql-alarm
skinparam monochrome true
+ Infra
++ aws
+++ AppSync
++++ DataSource (1)
++++ GraphqlApi (1)
++++ Resolver (5)
+++ CloudWatch
++++ MetricAlarm (1)
+++ DynamoDB
++++ Table (1)
+++ IAM
++++ Role (1)
++++ Policy (1)
+++ SNS
++++ Topic (1)
@endmindmap