@startmindmap
title Resources for project CloudFront WebSite HTTPS
skinparam monochrome true
+ Infra
++ aws
+++ S3
++++ Object (5)
++++ Bucket (1)
+++ ACM
++++ Certificate (1)
+++ CloudFront
++++ Distribution (1)
+++ Route53
++++ HostedZone (1)
++++ Record (2)
+++ Route53Domains
++++ Domain (1)
@endmindmap