@startmindmap
title Resources for project website-https
skinparam monochrome true
+ Infra
++ aws
+++ s3
++++ Bucket (1)
++++ Object (5)
+++ acm
++++ Certificate (1)
+++ route53Domain
++++ Domain (1)
+++ route53
++++ HostedZone (1)
++++ Record (2)
+++ cloudFront
++++ Distribution (1)
@endmindmap