@startmindmap
title Resources for project alb-lambda-cdk
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ InternetGateway (1)
++++ InternetGatewayAttachment (1)
++++ Route (2)
++++ RouteTable (2)
++++ RouteTableAssociation (2)
++++ SecurityGroup (1)
++++ SecurityGroupRuleIngress (1)
++++ Subnet (2)
++++ Vpc (1)
+++ ElasticLoadBalancingV2
++++ Listener (1)
++++ LoadBalancer (1)
++++ TargetGroup (1)
++++ TargetGroupAttachments (1)
+++ IAM
++++ Role (1)
+++ Lambda
++++ Function (1)
++++ Permission (1)
@endmindmap