@startmindmap
title Resources for project eventbridge-schedule-to-lambda
skinparam monochrome true
+ Infra
++ aws
+++ IAM
++++ Role (2)
+++ Lambda
++++ Function (1)
+++ Scheduler
++++ Schedule (1)
@endmindmap