exports.ResourcesExcludes = [
  "App::ContainerAppsAuthConfig",
  "Authorization::AccessReviewDefaultSetting",
  "Authorization::AccessReviewHistoryDefinitionById",
  "Authorization::AccessReviewScheduleDefinitionById",
  "Authorization::AccessReviewInstanceById",
  "Authorization::ScopeRoleAssignmentApprovalStepById",
  "Authorization::RoleAssignmentApprovalStepById",
  "Authorization::RoleAssignmentById",
  "Authorization::RoleAssignmentScheduleRequest",
  "Authorization::RoleEligibilityScheduleRequest",
  "Authorization::RoleManagementPolicy",
  "Authorization::RoleManagementPolicyAssignment",
  "Authorization::ScopeAccessReviewDefaultSetting",
  "Compute::VirtualMachineScaleSetVMExtension",
  "Compute::VirtualMachineScaleSetVMRunCommand",
  "ContainerRegistry::ConnectedRegistry",
  "ContainerService::PrivateEndpointConnection", // 400 Cluster cluster is not a private cluster.
  "ContainerService::OpenShiftManagedCluster", // 404
  "DBforPostgreSQL::PrivateEndpointConnection",
  "DBforPostgreSQL::ServerSecurityAlertPolicy",
  "DBforPostgreSQL::ServerKey",
  "DBforPostgreSQL::ServerAdministrator",
  "DBforPostgreSQL::VirtualNetworkRule",
  "DocumentDB::DatabaseAccountSqlDatabase",
  "DocumentDB::DatabaseAccountCassandraKeyspace",
  "DocumentDB::DatabaseAccountCassandraKeyspaceThroughput",
  "DocumentDB::DatabaseAccountCassandraTable",
  "DocumentDB::DatabaseAccountCassandraTableThroughput",
  "DocumentDB::DatabaseAccountGremlinDatabase",
  "DocumentDB::DatabaseAccountGremlinDatabaseThroughput",
  "DocumentDB::DatabaseAccountGremlinGraph",
  "DocumentDB::DatabaseAccountGremlinGraphThroughput",
  "DocumentDB::DatabaseAccountMongoDBCollection",
  "DocumentDB::DatabaseAccountMongoDBDatabase",
  "DocumentDB::DatabaseAccountMongoDBDatabaseThroughput",
  "DocumentDB::DatabaseAccountSqlContainer",
  "DocumentDB::DatabaseAccountSqlContainerThroughput",
  "DocumentDB::DatabaseAccountSqlDatabase",
  "DocumentDB::DatabaseAccountSqlDatabaseThroughput",
  "DocumentDB::DatabaseAccountTable",
  "DocumentDB::DatabaseAccountTableThroughput",
  "Network::AdminRule",
  "Network::ExpressRouteCrossConnection",
  "Network::ExpressRouteCrossConnectionPeering", //TODO 404 on list
  "Network::ExpressRoutePort",
  "Network::FirewallPolicyIdpsSignaturesOverride",
  "Network::InterfaceEndpoint",
  "Network::LoadBalancerBackendAddressPool", // set LoadBalancerBackendAddressPool in LoadBalancers
  "Network::ManagementGroupNetworkManagerConnection",
  "Network::InboundNatRule",
  "Network::NetworkManager",
  "Network::NetworkSecurityPerimeter",
  "Network::PublicIpAddress", // Renamed to PublicIPAddress
  "Network::SecurityRule",
  "Network::SubscriptionNetworkManagerConnection",
  "Network::UserRule",
  "Network::VirtualWAN", // Renamed to VirtualWan
  "OperationalInsights::DataCollectorLog", //404
  "OperationalInsights::DataSource", // Must specify a valid kind filter. For example, $filter=kind eq 'windowsPerformanceCounter'.
  "OperationalInsights::Table", // No registered resource provider found for location 'uksouth' and API version '2021-06-01'
  "PrivateEndpointConnection::DBforPostgreSQL", // No registered resource provider found for location 'centralus' and API version '2018-06-01' for type 'flexibleServers'. The supported api-versions are '2020-02-14-privatepreview, 2021-04-10-privatepreview, 2020-02-14-preview, 2020-11-05-preview, 2021-05-01-privatepreview, 2021-06-01-preview, 2021-06-01'. The supported locations are 'australiaeast, australiasoutheast, brazilsouth, uksouth, centralindia, centralus, eastasia, eastus, eastus2, francecentral, germanywestcentral, koreacentral, japaneast, japanwest, northcentralus, northeurope, norwayeast, southafricanorth, southcentralus, southeastasia, switzerlandnorth, swedencentral, uaenorth, uksouth, ukwest, westcentralus, westus, westus2, westus3, westeurope'.
  "Storage::BlobInventoryPolicy", //TODO 404 on list
  "KeyVault::PrivateEndpointConnection", // TODO 404
  "Web::CertificateCsr",
  "Web::ClassicMobileService",
  "Web::ContainerApp",
  "Web::KubeEnvironment",
  "Web::Domain",
  "Web::GetSourceControlSourceControl",
  "Web::GetPublishingUserPublishingUser",
  "Web::GlobalSubscriptionPublishingCredentials",
  "Web::ManagedHostingEnvironment",
  "Web::ProviderPublishingUser",
  "Web::ProviderSourceControl",
  "Web::Site",
  "Web::SiteBackupStatus",
  "Web::SiteBackupStatusSlot",
  "Web::SiteConfig",
  "Web::SiteConfigSlot",
  "Web::SiteDeployment",
  "Web::SiteDeploymentSlot",
  "Web::SiteHostNameBinding",
  "Web::SiteHostNameBindingSlot",
  "Web::SiteInstanceDeployment",
  "Web::SiteInstanceDeploymentSlot",
  "Web::SiteLogsConfig",
  "Web::SiteLogsConfigSlot",
  "Web::SitePremierAddOn",
  "Web::SitePremierAddOnSlot",
  "Web::SiteRelayServiceConnection",
  "Web::SiteRelayServiceConnectionSlot",
  "Web::SiteSlot",
  "Web::SiteSlotConfigNames",
  "Web::SiteSourceControl",
  "Web::SiteSourceControlSlot",
  "Web::SiteVNETConnection",
  "Web::SiteVNETConnectionSlot",
  "Web::ServerFarm",
  //TODO remove ?
  //"Web::ServerFarmRouteForVnet",
  "Web::WebAppOneDeployStatus",
  "Web::WebAppProcess",
];
