// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Account",
    group: "Organisations",
    name: "test account",
    readOnly: true,
    properties: ({}) => ({
      Email: "test@grucloud.com",
      Name: "test account",
    }),
  },
  {
    type: "Policy",
    group: "Organisations",
    properties: ({}) => ({
      Content: {
        Version: "2012-10-17",
        Statement: [
          {
            Sid: "Statement2",
            Effect: "Allow",
            Action: ["*"],
            Resource: ["*"],
          },
        ],
      },
      Description: "Allow all",
      Name: "my-policy",
      Type: "SERVICE_CONTROL_POLICY",
    }),
  },
  {
    type: "Policy",
    group: "Organisations",
    properties: ({}) => ({
      Content: {
        tags: {
          env: {
            tag_value: {
              "@@assign": ["prod", "dev"],
            },
          },
        },
      },
      Description: "My tag policy",
      Name: "my-tag-policy",
      Type: "TAG_POLICY",
    }),
  },
  {
    type: "PolicyAttachment",
    group: "Organisations",
    dependencies: ({}) => ({
      policy: "my-policy",
      organisationalUnit: "my-ou-test",
    }),
  },
  {
    type: "PolicyAttachment",
    group: "Organisations",
    dependencies: ({}) => ({
      policy: "my-policy",
      account: "test account",
    }),
  },
  {
    type: "OrganisationalUnit",
    group: "Organisations",
    name: "my-ou-test",
    readOnly: true,
    properties: ({}) => ({
      Name: "my-ou-test",
    }),
    dependencies: ({}) => ({
      root: "Root",
    }),
  },
  {
    type: "Root",
    group: "Organisations",
    name: "Root",
    readOnly: true,
    properties: ({}) => ({
      Name: "Root",
      PolicyTypes: [
        {
          Status: "ENABLED",
          Type: "TAG_POLICY",
        },
        {
          Status: "ENABLED",
          Type: "SERVICE_CONTROL_POLICY",
        },
      ],
    }),
  },
];
