@startmindmap
title Resources for project apigw-client-certificate
skinparam monochrome true
+ Infra
++ aws
+++ APIGateway
++++ ClientCertificate (1)
++++ RestApi (1)
++++ Stage (1)
+++ IAM
++++ Role (1)
+++ Lambda
++++ Function (1)
++++ Permission (1)
@endmindmap