@startmindmap
title Resources for project appsync-eventbridge
skinparam monochrome true
+ Infra
++ aws
+++ AppSync
++++ GraphqlApi (1)
++++ DataSource (1)
++++ Resolver (1)
+++ CloudWatchEvents
++++ EventBus (1)
+++ IAM
++++ Role (3)
@endmindmap