@startmindmap
title Resources for project securityGroup-simple
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ SecurityGroup (2)
++++ SecurityGroupRuleIngress (2)
++++ SecurityGroupRuleEgress (1)
++++ Vpc (1)
@endmindmap