// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "LogGroup",
    group: "CloudWatchLogs",
    properties: ({}) => ({
      logGroupName: "loggroupwithkmskey",
      retentionInDays: 1,
    }),
    dependencies: ({}) => ({
      kmsKey: "kms-key-aws-hub-and-spoke-demo",
    }),
  },
  {
    type: "Key",
    group: "KMS",
    name: "kms-key-aws-hub-and-spoke-demo",
    properties: ({ config }) => ({
      Description: "KMS Logs Key",
      Policy: {
        Id: "key-default-1",
        Statement: [
          {
            Action: "kms:*",
            Effect: "Allow",
            Principal: {
              AWS: `arn:aws:iam::${config.accountId()}:root`,
            },
            Resource: "*",
            Sid: "Enable IAM User Permissions",
          },
          {
            Action: [
              "kms:Encrypt*",
              "kms:Decrypt*",
              "kms:ReEncrypt*",
              "kms:GenerateDataKey*",
              "kms:Describe*",
            ],
            Effect: "Allow",
            Principal: {
              Service: `logs.${config.region}.amazonaws.com`,
            },
            Resource: "*",
            Sid: "Enable KMS to be used by CloudWatch Logs",
          },
        ],
        Version: "2012-10-17",
      },
    }),
  },
];
