@startmindmap
title Resources for project codebuild-simple
skinparam monochrome true
+ Infra
++ aws
+++ CodeBuild
++++ Project (1)
++++ ReportGroup (1)
+++ IAM
++++ Policy (1)
++++ Role (1)
+++ S3
++++ Bucket (1)
@endmindmap