@startmindmap
title Resources for project appsync-sqs
skinparam monochrome true
+ Infra
++ aws
+++ AppSync
++++ GraphqlApi (1)
++++ DataSource (1)
++++ Resolver (1)
+++ IAM
++++ Role (1)
+++ SQS
++++ Queue (1)
@endmindmap