// Generated by aws2gc
const { AwsProvider } = require("@grucloud/provider-aws");

const createResources = ({ provider }) => {
  const { config } = provider;

  provider.iam.makePolicy({
    name: config.iam.Policy.lambdaPolicy.name,
    properties: () => config.iam.Policy.lambdaPolicy.properties,
  });

  provider.iam.makeRole({
    name: config.iam.Role.lambdaRole.name,
    dependencies: ({ resources }) => ({
      policies: [resources.iam.Policy.lambdaPolicy],
    }),
    properties: () => config.iam.Role.lambdaRole.properties,
  });

  provider.acm.makeCertificate({
    name: config.acm.Certificate.grucloudOrg.name,
    properties: () => config.acm.Certificate.grucloudOrg.properties,
  });

  provider.route53Domain.useDomain({
    name: config.route53Domain.Domain.grucloudOrg.name,
  });

  provider.route53.makeHostedZone({
    name: config.route53.HostedZone.grucloudOrg.name,
    dependencies: ({ resources }) => ({
      domain: resources.route53Domain.Domain.grucloudOrg,
    }),
  });

  provider.route53.makeRecord({
    name: config.route53.Record.apiGatewayAliasRecord.name,
    dependencies: ({ resources }) => ({
      hostedZone: resources.route53.HostedZone.grucloudOrg,
      apiGatewayDomainName: resources.apigateway.DomainName.grucloudOrg,
    }),
  });

  provider.route53.makeRecord({
    name: config.route53.Record.certificateValidationGrucloudOrg.name,
    dependencies: ({ resources }) => ({
      hostedZone: resources.route53.HostedZone.grucloudOrg,
      certificate: resources.acm.Certificate.grucloudOrg,
    }),
  });

  provider.lambda.makeFunction({
    name: config.lambda.Function.myFunction.name,
    dependencies: ({ resources }) => ({
      role: resources.iam.Role.lambdaRole,
    }),
    properties: () => config.lambda.Function.myFunction.properties,
  });

  provider.apigateway.makeApi({
    name: config.apigateway.Api.myApi.name,
    properties: () => config.apigateway.Api.myApi.properties,
  });

  provider.apigateway.makeIntegration({
    name: config.apigateway.Integration.integrationLambda.name,
    dependencies: ({ resources }) => ({
      api: resources.apigateway.Api.myApi,
      lambdaFunction: resources.lambda.Function.myFunction,
    }),
    properties: () =>
      config.apigateway.Integration.integrationLambda.properties,
  });

  provider.apigateway.makeRoute({
    name: config.apigateway.Route.anyMyFunction.name,
    dependencies: ({ resources }) => ({
      api: resources.apigateway.Api.myApi,
      integration: resources.apigateway.Integration.integrationLambda,
    }),
    properties: () => config.apigateway.Route.anyMyFunction.properties,
  });

  provider.apigateway.makeStage({
    name: config.apigateway.Stage.myApiStageDev.name,
    dependencies: ({ resources }) => ({
      api: resources.apigateway.Api.myApi,
    }),
    properties: () => config.apigateway.Stage.myApiStageDev.properties,
  });

  provider.apigateway.makeDeployment({
    name: config.apigateway.Deployment.myApiDeployment.name,
    dependencies: ({ resources }) => ({
      api: resources.apigateway.Api.myApi,
      stage: resources.apigateway.Stage.myApiStageDev,
    }),
    properties: () => config.apigateway.Deployment.myApiDeployment.properties,
  });

  provider.apigateway.makeDomainName({
    name: config.apigateway.DomainName.grucloudOrg.name,
    dependencies: ({ resources }) => ({
      certificate: resources.acm.Certificate.grucloudOrg,
    }),
    properties: () => config.apigateway.DomainName.grucloudOrg.properties,
  });
};

exports.createResources = createResources;

exports.createStack = async ({ createProvider }) => {
  const provider = createProvider(AwsProvider, { config: require("./config") });
  createResources({
    provider,
  });

  return {
    provider,
  };
};
