@startmindmap
title Resources for project prometheus-simple
skinparam monochrome true
+ Infra
++ aws
+++ Aps
++++ AlertManagerDefinition (1)
++++ RuleGroupsNamespace (1)
++++ Workspace (1)
@endmindmap