// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Domain",
    group: "OpenSearch",
    properties: ({ config }) => ({
      AccessPolicies: {
        Version: "2012-10-17",
        Statement: [
          {
            Effect: "Deny",
            Principal: {
              AWS: "*",
            },
            Action: "es:*",
            Resource: `arn:aws:es:${
              config.region
            }:${config.accountId()}:domain/my-domain/*`,
          },
        ],
      },
      AdvancedSecurityOptions: {
        AnonymousAuthEnabled: false,
        Enabled: true,
        InternalUserDatabaseEnabled: true,
        MasterUserOptions: {
          MasterUserName: process.env.MY_DOMAIN_MASTER_USERNAME,
          MasterUserPassword: process.env.MY_DOMAIN_MASTER_USER_PASSWORD,
        },
      },
      AutoTuneOptions: {
        DesiredState: "ENABLED",
      },
      ClusterConfig: {
        ColdStorageOptions: {
          Enabled: false,
        },
        DedicatedMasterEnabled: false,
        InstanceCount: 3,
        InstanceType: "t3.small.search",
        WarmEnabled: false,
        ZoneAwarenessEnabled: false,
      },
      DomainName: "my-domain",
      EngineVersion: "OpenSearch_2.3",
    }),
  },
];
