@startmindmap
title Resources for project Lambda SQS
skinparam monochrome true
+ Infra
++ aws
+++ IAM
++++ Role (1)
++++ Policy (1)
+++ Lambda
++++ EventSourceMapping (1)
++++ Function (1)
+++ SQS
++++ Queue (1)
@endmindmap