@startmindmap
title Resources for project plantuml
skinparam monochrome true
+ Infra
++ azure
+++ OperationalInsights
++++ Workspace (1)
+++ Resources
++++ ResourceGroup (1)
+++ Web
++++ ContainerApp (1)
++++ KubeEnvironment (1)
@endmindmap