// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

const createResources = ({ provider }) => {
  provider.SQS.makeQueue({
    name: "my-queue",
    properties: ({}) => ({
      tags: {
        "my-tag": "my-value",
      },
    }),
  });
};

exports.createResources = createResources;
