@startmindmap
title Resources for project http-lambda
skinparam monochrome true
+ Infra
++ aws
+++ IAM
++++ Policy (1)
++++ Role (1)
+++ ACM
++++ Certificate (1)
+++ Route53Domains
++++ Domain (1)
+++ Route53
++++ HostedZone (1)
++++ Record (2)
+++ Lambda
++++ Function (1)
+++ ApiGatewayV2
++++ Api (1)
++++ Integration (1)
++++ Route (1)
++++ Stage (1)
++++ Deployment (1)
++++ DomainName (1)
@endmindmap