@startmindmap
title Resources for project http-lambda
skinparam monochrome true
+ Infra
++ aws
+++ route53Domain
++++ Domain (1)
+++ route53
++++ HostedZone (1)
++++ Record (2)
+++ acm
++++ Certificate (1)
+++ iam
++++ Policy (1)
++++ Role (1)
+++ lambda
++++ Function (1)
+++ apiGatewayV2
++++ Api (1)
++++ DomainName (1)
++++ Integration (1)
++++ Route (1)
++++ Stage (1)
++++ ApiMapping (1)
++++ Deployment (1)
@endmindmap