@startmindmap
title Resources for project sfn-eventbridge
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchEvents
++++ EventBus (1)
++++ Rule (1)
++++ Target (1)
+++ CloudWatchLogs
++++ LogGroup (1)
+++ DynamoDB
++++ Table (1)
+++ IAM
++++ Role (5)
+++ StepFunctions
++++ StateMachine (2)
@endmindmap