@startmindmap
title Resources for project postgres-stateless
skinparam monochrome true
+ Infra
++ aws
+++ ec2
++++ KeyPair (1)
+++++ kp
++++ Vpc (1)
+++++ vpc
++++ InternetGateway (1)
+++++ internet-gateway
++++ Subnet (4)
+++++ subnet-public-a
+++++ subnet-public-b
+++++ subnet-private-a
+++++ subnet-private-b
++++ RouteTable (3)
+++++ route-table-public
+++++ route-table-private-a
+++++ route-table-private-b
++++ Route (3)
+++++ route-public
+++++ route-private-a
+++++ route-private-b
++++ ElasticIpAddress (2)
+++++ iep
+++++ eip-bastion
++++ NatGateway (1)
+++++ nat-gateway
++++ SecurityGroup (2)
+++++ security-group-public
+++++ security-group-postgres
++++ SecurityGroupRuleIngress (2)
+++++ sg-rule-ingress-ssh-bastion
+++++ sg-rule-ingress-postgres
++++ Image (1)
+++++ Amazon Linux 2
++++ Instance (1)
+++++ bastion
+++ rds
++++ DBSubnetGroup (1)
+++++ subnet-group-postgres-stateless
++++ DBCluster (1)
+++++ cluster-postgres-stateless
@endmindmap