@startmindmap
title Resources for project backup-simple
skinparam monochrome true
+ Infra
++ aws
+++ Backup
++++ BackupPlan (1)
++++ BackupSelection (1)
++++ BackupVault (1)
++++ BackupVaultLockConfiguration (1)
++++ BackupVaultPolicy (1)
++++ Framework (1)
++++ GlobalSettings (1)
++++ ReportPlan (1)
+++ Config
++++ ConfigurationRecorder (1)
++++ ConfigurationRecorderStatus (1)
++++ DeliveryChannel (1)
+++ IAM
++++ Role (1)
+++ S3
++++ Bucket (3)
@endmindmap