// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Role",
    group: "IAM",
    properties: ({}) => ({
      RoleName: "sam-app-ApplicationFunctionRole-1OYVLSFKOAUGQ",
      AssumeRolePolicyDocument: {
        Version: "2012-10-17",
        Statement: [
          {
            Effect: "Allow",
            Principal: {
              Service: "lambda.amazonaws.com",
            },
            Action: "sts:AssumeRole",
          },
        ],
      },
      AttachedPolicies: [
        {
          PolicyName: "AWSXrayWriteOnlyAccess",
          PolicyArn: "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess",
        },
        {
          PolicyName: "AWSLambdaBasicExecutionRole",
          PolicyArn:
            "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
        },
        {
          PolicyName: "AWSLambdaKinesisExecutionRole",
          PolicyArn:
            "arn:aws:iam::aws:policy/service-role/AWSLambdaKinesisExecutionRole",
        },
      ],
    }),
  },
  {
    type: "Stream",
    group: "Kinesis",
    properties: ({}) => ({
      StreamName: "sam-app-KinesisStream-XFWKt5wUL37R",
      ShardCount: 1,
    }),
  },
  {
    type: "StreamConsumer",
    group: "Kinesis",
    properties: ({}) => ({
      ConsumerName: "ApplicationConsumer",
    }),
    dependencies: ({}) => ({
      stream: "sam-app-KinesisStream-XFWKt5wUL37R",
    }),
  },
  {
    type: "EventSourceMapping",
    group: "Lambda",
    properties: ({}) => ({
      BatchSize: 100,
      BisectBatchOnFunctionError: false,
      MaximumRecordAgeInSeconds: -1,
      MaximumRetryAttempts: -1,
      ParallelizationFactor: 1,
      StartingPosition: "LATEST",
      TumblingWindowInSeconds: 0,
    }),
    dependencies: ({}) => ({
      lambdaFunction: "sam-app-ApplicationFunction-LL5g6gqeQgsc",
      kinesisStreamConsumer:
        "sam-app-KinesisStream-XFWKt5wUL37R::ApplicationConsumer",
    }),
  },
  {
    type: "Function",
    group: "Lambda",
    properties: ({}) => ({
      Configuration: {
        TracingConfig: {
          Mode: "Active",
        },
        FunctionName: "sam-app-ApplicationFunction-LL5g6gqeQgsc",
        Runtime: "nodejs12.x",
        Handler: "app.lambdaHandler",
      },
    }),
    dependencies: ({}) => ({
      role: "sam-app-ApplicationFunctionRole-1OYVLSFKOAUGQ",
    }),
  },
];
