@startmindmap
title Resources for project vm-vault
skinparam monochrome true
+ Infra
++ azure
+++ Compute
++++ SshPublicKey (1)
++++ VirtualMachine (1)
+++ Network
++++ NetworkInterface (1)
++++ NetworkSecurityGroup (1)
++++ PublicIPAddress (1)
++++ Subnet (1)
++++ VirtualNetwork (1)
+++ Resources
++++ ResourceGroup (1)
@endmindmap