@startmindmap
title Resources for project sfn-eventbridge
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchEvents
++++ EventBus (1)
++++ Rule (1)
++++ Target (1)
+++ CloudWatchLogs
++++ LogGroup (1)
+++ IAM
++++ Role (1)
+++ StepFunctions
++++ StateMachine (1)
@endmindmap