@startuml gc-new-google
!theme plain

skinparam svgLinkTarget _blank

card "gc new for GCP" {
start

:""gc new"";
: Select GCP;
: Enter the project's name;


partition "Is the gcloud CLI installed ?" {
repeat :""gcloud version"";
backward:  Visit [[https://https://cloud.google.com/sdk/docs/install]];
repeat while (is installed ?) is (no) 
->yes;
}

partition "Is Authenticated ? " {

repeat :""gcloud auth list"";
backward:  ""gloud auth login"";
repeat while (is authenticated ?) is (no) 

}

partition "Select Project Id " {
 
fork
  :""gcloud projects list"";
fork again
  :""gcloud config get-value project"";
end fork
: Prompt for project from list;
}

partition "Select Region " {
fork
  :""gcloud compute regions list"";
fork again
  :""gcloud config get-value compute/region"";
end fork
: Prompt for region from list;
}

partition "Select Zone " {
 fork
  :""gcloud compute zones list"";
fork again
  :""gcloud config get-value compute/zone"";
end fork
: Prompt for zone from list;
}

: Save files; 
note right
* ""config.js""
* ""auth.env""
* ""iac.js""
* ""resources.js""
* ""package.json""
* etc ...
end note 

: ""npm install"";
end

note right
Next Steps:
* ""gc list""
* ""gc gencode""
* ""gc destroy""
* ""gc apply""
end note 
}
@enduml