// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

const createResources = ({ provider }) => {
  provider.Resources.makeResourceGroup({
    name: "rg-disk-encrypted",
  });
};

exports.createResources = createResources;
