@startmindmap
title Resources for project sns-subscription-filter-policy
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchLogs
++++ LogGroup (1)
+++ Firehose
++++ DeliveryStream (1)
+++ IAM
++++ Policy (1)
++++ Role (2)
+++ S3
++++ Bucket (1)
+++ SNS
++++ Topic (1)
++++ Subscription (1)
@endmindmap