// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Account",
    group: "Organisations",
    name: "frederic heem",
    readOnly: true,
    properties: ({}) => ({
      Email: "frederic.heem@gmail.com",
      Name: "frederic heem",
    }),
  },
  { type: "Account", group: "SecurityHub" },
  {
    type: "FindingAggregator",
    group: "SecurityHub",
    properties: ({}) => ({
      FindingAggregationRegion: "us-east-1",
      RegionLinkingMode: "SPECIFIED_REGIONS",
      Regions: ["eu-west-2"],
    }),
    dependencies: ({}) => ({
      securityHubAccount: "default",
    }),
  },
  {
    type: "OrganizationAdminAccount",
    group: "SecurityHub",
    dependencies: ({}) => ({
      accountDelegated: "frederic heem",
    }),
  },
  {
    type: "OrganizationConfiguration",
    group: "SecurityHub",
    properties: ({}) => ({
      AutoEnable: false,
      AutoEnableStandards: "NONE",
    }),
    dependencies: ({}) => ({
      securityHubAccount: "default",
    }),
  },
  {
    type: "StandardsSubscription",
    group: "SecurityHub",
    properties: ({}) => ({
      StandardsArn:
        "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0",
    }),
    dependencies: ({}) => ({
      securityHubAccount: "default",
    }),
  },
  {
    type: "StandardsSubscription",
    group: "SecurityHub",
    properties: ({ config }) => ({
      StandardsArn: `arn:aws:securityhub:${config.region}::standards/aws-foundational-security-best-practices/v/1.0.0`,
    }),
    dependencies: ({}) => ({
      securityHubAccount: "default",
    }),
  },
];
