// Generated by aws2gc
const { get } = require("rubico");
const { AwsProvider } = require("@grucloud/provider-aws");

const createResources = ({ provider }) => {
  provider.EC2.makeVpc({
    name: get("config.EC2.Vpc.vpc.name"),
    namespace: "VPC",
    properties: get("config.EC2.Vpc.vpc.properties"),
  });

  provider.EC2.makeSubnet({
    name: get("config.EC2.Subnet.subnetPrivateA.name"),
    namespace: "VPC",
    properties: get("config.EC2.Subnet.subnetPrivateA.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
    }),
  });

  provider.EC2.makeSubnet({
    name: get("config.EC2.Subnet.subnetPrivateB.name"),
    namespace: "VPC",
    properties: get("config.EC2.Subnet.subnetPrivateB.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
    }),
  });

  provider.EC2.makeSubnet({
    name: get("config.EC2.Subnet.subnetPublicA.name"),
    namespace: "VPC",
    properties: get("config.EC2.Subnet.subnetPublicA.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
    }),
  });

  provider.EC2.makeSubnet({
    name: get("config.EC2.Subnet.subnetPublicB.name"),
    namespace: "VPC",
    properties: get("config.EC2.Subnet.subnetPublicB.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
    }),
  });

  provider.EC2.makeElasticIpAddress({
    name: get("config.EC2.ElasticIpAddress.iep.name"),
    namespace: "VPC",
  });

  provider.EC2.makeInternetGateway({
    name: get("config.EC2.InternetGateway.internetGateway.name"),
    namespace: "VPC",
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
    }),
  });

  provider.EC2.makeNatGateway({
    name: get("config.EC2.NatGateway.natGateway.name"),
    namespace: "VPC",
    dependencies: ({ resources }) => ({
      subnet: resources.EC2.Subnet.subnetPublicA,
      eip: resources.EC2.ElasticIpAddress.iep,
    }),
  });

  provider.EC2.makeRouteTable({
    name: get("config.EC2.RouteTable.routeTablePrivateA.name"),
    namespace: "VPC",
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
      subnets: [resources.EC2.Subnet.subnetPrivateA],
    }),
  });

  provider.EC2.makeRouteTable({
    name: get("config.EC2.RouteTable.routeTablePrivateB.name"),
    namespace: "VPC",
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
      subnets: [resources.EC2.Subnet.subnetPrivateB],
    }),
  });

  provider.EC2.makeRouteTable({
    name: get("config.EC2.RouteTable.routeTablePublic.name"),
    namespace: "VPC",
    dependencies: ({ resources }) => ({
      vpc: resources.EC2.Vpc.vpc,
      subnets: [
        resources.EC2.Subnet.subnetPublicA,
        resources.EC2.Subnet.subnetPublicB,
      ],
    }),
  });

  provider.EC2.makeRoute({
    name: get("config.EC2.Route.routePrivateA.name"),
    namespace: "VPC",
    properties: get("config.EC2.Route.routePrivateA.properties"),
    dependencies: ({ resources }) => ({
      routeTable: resources.EC2.RouteTable.routeTablePrivateA,
      natGateway: resources.EC2.NatGateway.natGateway,
    }),
  });

  provider.EC2.makeRoute({
    name: get("config.EC2.Route.routePrivateB.name"),
    namespace: "VPC",
    properties: get("config.EC2.Route.routePrivateB.properties"),
    dependencies: ({ resources }) => ({
      routeTable: resources.EC2.RouteTable.routeTablePrivateB,
      natGateway: resources.EC2.NatGateway.natGateway,
    }),
  });

  provider.EC2.makeRoute({
    name: get("config.EC2.Route.routePublic.name"),
    namespace: "VPC",
    properties: get("config.EC2.Route.routePublic.properties"),
    dependencies: ({ resources }) => ({
      routeTable: resources.EC2.RouteTable.routeTablePublic,
      ig: resources.EC2.InternetGateway.internetGateway,
    }),
  });
};

exports.createResources = createResources;

exports.createStack = async ({ createProvider }) => {
  const provider = createProvider(AwsProvider, { config: require("./config") });
  createResources({
    provider,
  });

  return {
    provider,
  };
};
