@startmindmap
title Resources for project global-accelerator-loadbalancer
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ SecurityGroup (1)
++++ Subnet (2)
++++ Vpc (1)
+++ ElasticLoadBalancingV2
++++ Listener (1)
++++ LoadBalancer (1)
++++ TargetGroup (1)
+++ GlobalAccelerator
++++ Accelerator (1)
++++ EndpointGroup (1)
++++ Listener (1)
@endmindmap