@startmindmap
title Resources for project kendra-simple
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchLogs
++++ LogGroup (1)
+++ IAM
++++ Role (5)
++++ Policy (5)
+++ Kendra
++++ DataSource (1)
++++ Experience (1)
++++ Faq (1)
++++ Index (1)
++++ QuerySuggestionsBlockList (1)
+++ S3
++++ Bucket (1)
++++ Object (2)
@endmindmap