@startmindmap
title Resources for project budget-simple
skinparam monochrome true
+ Infra
++ aws
+++ Budgets
++++ Budget (1)
+++ IAM
++++ Role (1)
++++ InstanceProfile (1)
+++ SNS
++++ Topic (1)
@endmindmap