@startmindmap
title Resources for project s3-eventbridge
skinparam monochrome true
+ Infra
++ aws
+++ CloudTrail
++++ Trail (1)
+++ CloudWatchEvents
++++ Rule (1)
++++ Target (1)
+++ S3
++++ Bucket (2)
+++ SQS
++++ Queue (1)
@endmindmap