@startmindmap
title Resources for project codedeploy-ecs
skinparam monochrome true
+ Infra
++ aws
+++ CodeDeploy
++++ Application (1)
++++ DeploymentGroup (1)
+++ EC2
++++ InternetGateway (1)
++++ InternetGatewayAttachment (1)
++++ Route (1)
++++ RouteTable (1)
++++ RouteTableAssociation (2)
++++ SecurityGroup (3)
++++ SecurityGroupRuleIngress (4)
++++ Subnet (2)
++++ Vpc (1)
+++ ECS
++++ Cluster (1)
++++ Service (1)
++++ TaskDefinition (1)
+++ ElasticLoadBalancingV2
++++ Listener (1)
++++ LoadBalancer (1)
++++ TargetGroup (3)
+++ IAM
++++ Role (2)
@endmindmap