@startmindmap
title Resources for project eventbridge-sfn-terraform
skinparam monochrome true
+ Infra
++ aws
+++ CloudWatchEvents
++++ Rule (1)
++++ Target (1)
+++ CloudWatchLogs
++++ LogGroup (1)
+++ IAM
++++ Role (2)
++++ Policy (2)
+++ StepFunctions
++++ StateMachine (1)
@endmindmap