@startmindmap
title Resources for project hostedzone-private
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ Vpc (2)
+++ Route53
++++ HostedZone (1)
++++ ZoneVpcAssociation (1)
+++ Route53Domains
++++ Domain (1)
@endmindmap