@startmindmap
title Resources for project ECS created by ecs-cli
skinparam monochrome true
+ Infra
++ aws
+++ AutoScaling
++++ AutoScalingGroup (1)
++++ LaunchConfiguration (1)
+++ EC2
++++ InternetGateway (1)
++++ InternetGatewayAttachment (1)
++++ Route (1)
++++ RouteTable (1)
++++ RouteTableAssociation (2)
++++ SecurityGroup (1)
++++ SecurityGroupRuleIngress (1)
++++ Subnet (2)
++++ Vpc (1)
+++ ECS
++++ Cluster (1)
+++ IAM
++++ InstanceProfile (1)
++++ Role (1)
@endmindmap