// Generated by aws2gc
const { get } = require("rubico");
const { AwsProvider } = require("@grucloud/provider-aws");

const createResources = ({ provider }) => {
  provider.iam.makeRole({
    name: get("config.iam.Role.roleEcs.name"),
    properties: get("config.iam.Role.roleEcs.properties"),
  });

  provider.iam.makeInstanceProfile({
    name: get("config.iam.InstanceProfile.roleEcs.name"),
    dependencies: ({ resources }) => ({
      roles: [resources.iam.Role.roleEcs],
    }),
  });

  provider.ec2.makeVpc({
    name: get("config.ec2.Vpc.vpc.name"),
    properties: get("config.ec2.Vpc.vpc.properties"),
  });

  provider.ec2.makeSubnet({
    name: get("config.ec2.Subnet.pubSubnetAz1.name"),
    properties: get("config.ec2.Subnet.pubSubnetAz1.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.ec2.Vpc.vpc,
    }),
  });

  provider.ec2.makeSubnet({
    name: get("config.ec2.Subnet.pubSubnetAz2.name"),
    properties: get("config.ec2.Subnet.pubSubnetAz2.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.ec2.Vpc.vpc,
    }),
  });

  provider.ec2.makeKeyPair({
    name: get("config.ec2.KeyPair.kpEcs.name"),
  });

  provider.ec2.makeSecurityGroup({
    name: get("config.ec2.SecurityGroup.ecsSecurityGroup.name"),
    properties: get("config.ec2.SecurityGroup.ecsSecurityGroup.properties"),
    dependencies: ({ resources }) => ({
      vpc: resources.ec2.Vpc.vpc,
    }),
  });

  provider.ec2.makeSecurityGroupRuleIngress({
    name: get(
      "config.ec2.SecurityGroupRuleIngress.ecsSecurityGroupRuleIngressTcp_80V4.name"
    ),
    properties: get(
      "config.ec2.SecurityGroupRuleIngress.ecsSecurityGroupRuleIngressTcp_80V4.properties"
    ),
    dependencies: ({ resources }) => ({
      securityGroup: resources.ec2.SecurityGroup.ecsSecurityGroup,
    }),
  });

  provider.ec2.makeLaunchTemplate({
    name: get("config.ec2.LaunchTemplate.ltEc2Micro.name"),
    properties: get("config.ec2.LaunchTemplate.ltEc2Micro.properties"),
    dependencies: ({ resources }) => ({
      keyPair: resources.ec2.KeyPair.kpEcs,
      iamInstanceProfile: resources.iam.InstanceProfile.roleEcs,
    }),
  });

  provider.autoscaling.makeAutoScalingGroup({
    name: get("config.autoscaling.AutoScalingGroup.asg.name"),
    properties: get("config.autoscaling.AutoScalingGroup.asg.properties"),
    dependencies: ({ resources }) => ({
      subnets: [
        resources.ec2.Subnet.pubSubnetAz1,
        resources.ec2.Subnet.pubSubnetAz2,
      ],
    }),
  });
};

exports.createResources = createResources;

exports.createStack = async ({ createProvider }) => {
  const provider = createProvider(AwsProvider, { config: require("./config") });
  createResources({
    provider,
  });

  return {
    provider,
  };
};
