@startmindmap
title Resources for project autoScalingGroup
skinparam monochrome true
+ Infra
++ aws
+++ iam
++++ Role (1)
++++ InstanceProfile (1)
+++ ec2
++++ Vpc (1)
++++ Subnet (2)
++++ KeyPair (1)
++++ SecurityGroup (1)
++++ SecurityGroupRuleIngress (1)
++++ LaunchTemplate (1)
+++ autoscaling
++++ AutoScalingGroup (1)
@endmindmap