@startmindmap
title Resources for project aks-application-gateway
skinparam monochrome true
+ Infra
++ azure
+++ Authorization
++++ RoleAssignment (1)
+++ ContainerService
++++ ManagedCluster (1)
+++ Resources
++++ ResourceGroup (1)
@endmindmap