@startmindmap
title Resources for project codecommit-simple
skinparam monochrome true
+ Infra
++ aws
+++ CodeCommit
++++ ApprovalRuleTemplate (1)
++++ ApprovalRuleTemplateAssociation (1)
++++ Repository (1)
++++ RepositoryTriggers (1)
+++ SNS
++++ Topic (1)
@endmindmap