@startmindmap
title Resources for project apigw-lambda-json-xml-vtl-transformation
skinparam monochrome true
+ Infra
++ aws
+++ APIGateway
++++ RestApi (1)
++++ Stage (2)
+++ CloudWatchLogs
++++ LogGroup (1)
+++ IAM
++++ Role (2)
+++ Lambda
++++ Function (1)
++++ Permission (1)
@endmindmap