@startmindmap
title Resources for project cloudfront-distribution-sample
skinparam monochrome true
+ Infra
++ aws
+++ ACM
++++ Certificate (1)
+++ CloudFront
++++ Distribution (1)
++++ KeyGroup (1)
++++ MonitoringSubscription (1)
++++ OriginAccessIdentity (1)
++++ PublicKey (1)
+++ Route53
++++ HostedZone (1)
++++ Record (1)
+++ Route53Domains
++++ Domain (1)
+++ S3
++++ Bucket (1)
@endmindmap