@startmindmap
title Resources for project gateway-event-bus
skinparam monochrome true
+ Infra
++ aws
+++ ApiGatewayV2
++++ Api (1)
++++ Stage (1)
++++ Deployment (1)
++++ Integration (1)
++++ Route (1)
+++ CloudWatchEvents
++++ EventBus (1)
++++ Rule (1)
+++ CloudWatchLogs
++++ LogGroup (2)
+++ IAM
++++ Role (2)
+++ Lambda
++++ Function (1)
@endmindmap