@startmindmap
title Resources for project graphql
skinparam monochrome true
+ Infra
++ aws
+++ IAM
++++ Policy (1)
++++ Role (1)
+++ AppSync
++++ GraphqlApi (1)
++++ ApiKey (1)
++++ DataSource (1)
@endmindmap