@startmindmap
title Resources for project graphql
skinparam monochrome true
+ Infra
++ aws
+++ AppSync
++++ GraphqlApi (1)
++++ DataSource (1)
++++ Resolver (5)
+++ DynamoDB
++++ Table (1)
+++ IAM
++++ Role (2)
+++ Lambda
++++ Function (1)
@endmindmap