@startmindmap
title Resources for project graphql
skinparam monochrome true
+ Infra
++ aws
+++ IAM
++++ Policy (2)
++++ Role (3)
+++ DynamoDB
++++ Table (1)
+++ AppSync
++++ GraphqlApi (1)
++++ ApiKey (1)
++++ Resolver (5)
++++ DataSource (1)
+++ Lambda
++++ Function (1)
@endmindmap