@startmindmap
title Resources for project securityGroupDefault
skinparam monochrome true
+ Infra
++ aws
+++ ec2
++++ Vpc (1)
++++ SecurityGroup (1)
++++ SecurityGroupRuleIngress (1)
++++ SecurityGroupRuleEgress (1)
@endmindmap