@startmindmap
title Resources for project ec2-vpc
skinparam monochrome true
+ Infra
++ aws
+++ EC2
++++ KeyPair (1)
++++ Volume (1)
++++ VolumeAttachment (1)
++++ Vpc (1)
++++ InternetGateway (1)
++++ InternetGatewayAttachment (1)
++++ Subnet (1)
++++ RouteTable (1)
++++ RouteTableAssociation (1)
++++ Route (1)
++++ SecurityGroup (1)
++++ SecurityGroupRuleIngress (2)
++++ ElasticIpAddress (1)
++++ ElasticIpAddressAssociation (1)
++++ Instance (1)
@endmindmap