@startmindmap
title Resources for project eventbridge-schedule-to-eventbridge-cdk
skinparam monochrome true
+ Infra
++ aws
+++ IAM
++++ Role (1)
+++ Scheduler
++++ Schedule (1)
++++ ScheduleGroup (1)
@endmindmap