// Generated by 'gc gencode'
const {} = require("rubico");
const {} = require("rubico/x");

exports.createResources = () => [
  {
    type: "Policy",
    group: "IAM",
    name: "AmazonEC2ReadOnlyAccess",
    readOnly: true,
    properties: ({}) => ({
      Arn: "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess",
    }),
  },
  {
    type: "User",
    group: "IAM",
    name: "my-test-user",
    properties: ({}) => ({
      Path: "/",
      Tags: [
        {
          Key: "mytag",
          Value: "myvalue",
        },
      ],
    }),
    dependencies: () => ({
      policies: ["AmazonEC2ReadOnlyAccess"],
    }),
  },
];
