@startmindmap
title Resources for project securityhub-simple
skinparam monochrome true
+ Infra
++ aws
+++ Organisations
++++ Account (2)
+++ SecurityHub
++++ Account (1)
++++ FindingAggregator (1)
++++ Member (1)
++++ OrganizationAdminAccount (1)
++++ OrganizationConfiguration (1)
++++ ProductSubscription (1)
++++ StandardsControl (1)
++++ StandardsSubscription (2)
@endmindmap