// Generated by aws2gc
const assert = require("assert");
const { AwsProvider } = require("@grucloud/provider-aws");

const createResources = async ({ provider }) => {
  const { config } = provider;

  const grucloudOrg = provider.route53.makeHostedZone({
    name: config.grucloudOrg.name,
    properties: () => config.grucloudOrg.properties,
  });

  const txtGrucloudOrg = provider.route53.makeRecord({
    name: config.txtGrucloudOrg.name,
    dependencies: {
      hostedZone: grucloudOrg,
    },
    properties: () => config.txtGrucloudOrg.properties,
  });

  return {
    grucloudOrg,
    txtGrucloudOrg,
  };
};

exports.createResources = createResources;

exports.createStack = async () => {
  const provider = AwsProvider({ config: require("./config") });
  const resources = await createResources({
    provider,
  });

  return {
    provider,
    resources,
  };
};
