@startmindmap
title Resources for project transfer-sftp-s3
skinparam monochrome true
+ Infra
++ aws
+++ IAM
++++ Role (2)
+++ S3
++++ Bucket (1)
+++ Transfer
++++ Server (1)
++++ User (1)
++++ Workflow (1)
@endmindmap