@startmindmap
title Resources for project AWS Load Balancer
skinparam monochrome true
+ Infra
++ aws
+++ AutoScaling
++++ AutoScalingGroup (1)
++++ AutoScalingAttachment (2)
+++ ACM
++++ Certificate (1)
+++ EC2
++++ Vpc (1)
++++ InternetGateway (1)
++++ Subnet (2)
++++ RouteTable (1)
++++ RouteTableAssociation (2)
++++ Route (1)
++++ SecurityGroup (1)
++++ LaunchTemplate (1)
+++ ELBv2
++++ LoadBalancer (1)
++++ TargetGroup (2)
++++ Listener (2)
++++ Rule (3)
+++ Route53
++++ HostedZone (1)
++++ Record (1)
+++ Route53Domains
++++ Domain (1)
@endmindmap