@startmindmap
title Resources for project appstream-stack
skinparam monochrome true
+ Infra
++ aws
+++ AppStream
++++ Entitlement (1)
++++ Fleet (1)
++++ Stack (1)
++++ User (1)
++++ UserStackAssociation (1)
+++ EC2
++++ Vpc (1)
++++ Subnet (2)
++++ SecurityGroup (1)
+++ IAM
++++ Role (3)
@endmindmap